/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.crystalnexus.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.crystalnexus.block.ZeroPointBlock;
import net.crystalnexus.block.WarpPadBlock;
import net.crystalnexus.block.UltimaSmelterBlock;
import net.crystalnexus.block.TurbineBlock;
import net.crystalnexus.block.TesseractOutputBlock;
import net.crystalnexus.block.TesseractBlock;
import net.crystalnexus.block.TarrockWallBlock;
import net.crystalnexus.block.TarrockStairsBlock;
import net.crystalnexus.block.TarrockSoilBlock;
import net.crystalnexus.block.TarrockSlabBlock;
import net.crystalnexus.block.TarrockButtonBlock;
import net.crystalnexus.block.TarrockBricksBlock;
import net.crystalnexus.block.TarrockBrickWallBlock;
import net.crystalnexus.block.TarrockBrickStairsBlock;
import net.crystalnexus.block.TarrockBrickSlabBlock;
import net.crystalnexus.block.TarrockBlock;
import net.crystalnexus.block.TankBlock;
import net.crystalnexus.block.SulfurOreBlock;
import net.crystalnexus.block.SteamEngineUpgradeBlock;
import net.crystalnexus.block.SteamEngineBlock;
import net.crystalnexus.block.SteamCollectorBlock;
import net.crystalnexus.block.SteamChamberBlock;
import net.crystalnexus.block.SteamBlock;
import net.crystalnexus.block.SmoothTarrockWallBlock;
import net.crystalnexus.block.SmoothTarrockStairsBlock;
import net.crystalnexus.block.SmoothTarrockSlabBlock;
import net.crystalnexus.block.SmoothTarrockBlock;
import net.crystalnexus.block.SmartSplitterBlock;
import net.crystalnexus.block.SingularityMatrixBlock;
import net.crystalnexus.block.SingularityCompressorBlock;
import net.crystalnexus.block.SiliconOreBlock;
import net.crystalnexus.block.RubberBlockBlock;
import net.crystalnexus.block.ReactorWasteOutputBlock;
import net.crystalnexus.block.ReactorFluidInputBlock;
import net.crystalnexus.block.ReactorEnergyOutputBlock;
import net.crystalnexus.block.ReactorCoreBlock;
import net.crystalnexus.block.ReactorComputerBlock;
import net.crystalnexus.block.ReactorBlockBlock;
import net.crystalnexus.block.ReactionEnergyInputBlock;
import net.crystalnexus.block.ReactionChamberCoreBlock;
import net.crystalnexus.block.ReactionChamberComputerBlock;
import net.crystalnexus.block.ReactionChamberBlockBlock;
import net.crystalnexus.block.RawCrystalBlockStairsBlock;
import net.crystalnexus.block.RawCrystalBlockSlabBlock;
import net.crystalnexus.block.RawCrystalBlockBlock;
import net.crystalnexus.block.QuantumMinerBlock;
import net.crystalnexus.block.PolymerBlockBlock;
import net.crystalnexus.block.PistonGeneratorBlock;
import net.crystalnexus.block.PipeStraightBlock;
import net.crystalnexus.block.PipeJunctionBlock;
import net.crystalnexus.block.OreProcessorBlock;
import net.crystalnexus.block.OilNodeBlock;
import net.crystalnexus.block.NodeMinerBlock;
import net.crystalnexus.block.NodeExtractorBlock;
import net.crystalnexus.block.MultiblockResearchStationBlock;
import net.crystalnexus.block.MetallurgicRecrystallizerBlock;
import net.crystalnexus.block.MatterTransmutationTableBlock;
import net.crystalnexus.block.MachineblockBlock;
import net.crystalnexus.block.MachineFrameBlock;
import net.crystalnexus.block.MachineEnergyInputBlock;
import net.crystalnexus.block.MachineCoreBlock;
import net.crystalnexus.block.LavaNodeBlock;
import net.crystalnexus.block.ItemElevatorDownBlock;
import net.crystalnexus.block.ItemElevatorBlock;
import net.crystalnexus.block.ItemCollectorBlock;
import net.crystalnexus.block.IronSmelterBlock;
import net.crystalnexus.block.IronNodeBlock;
import net.crystalnexus.block.InvertiumSmelterBlock;
import net.crystalnexus.block.InvertiumMachineFrameBlock;
import net.crystalnexus.block.InvertiumBlockBlock;
import net.crystalnexus.block.InverterBlock;
import net.crystalnexus.block.InvertPistonGeneratorBlock;
import net.crystalnexus.block.HyperMachineFrameBlock;
import net.crystalnexus.block.GoldNodeBlock;
import net.crystalnexus.block.GasolineBlock;
import net.crystalnexus.block.FluidPackagerBlock;
import net.crystalnexus.block.FactoryOutputControllerBlock;
import net.crystalnexus.block.FactoryItemControllerBlock;
import net.crystalnexus.block.FactoryControllerBlock;
import net.crystalnexus.block.ExtractinatorBlock;
import net.crystalnexus.block.EnergySplitterBlock;
import net.crystalnexus.block.EnergyRefractorBlock;
import net.crystalnexus.block.EnergyExtractorBlock;
import net.crystalnexus.block.EnergyCableMk2Block;
import net.crystalnexus.block.EnergyCableBlock;
import net.crystalnexus.block.EEMatterBlockBlock;
import net.crystalnexus.block.EEBatteryBlock;
import net.crystalnexus.block.DustSeparatorBlock;
import net.crystalnexus.block.DepotUploaderBlock;
import net.crystalnexus.block.DepotDownloaderBlock;
import net.crystalnexus.block.CrystalizedAlloyBlockBlock;
import net.crystalnexus.block.CrystalSmelterBlock;
import net.crystalnexus.block.CrystalPurifierBlock;
import net.crystalnexus.block.CrystalMachineFrameBlock;
import net.crystalnexus.block.CrystalGuideBlock;
import net.crystalnexus.block.CrystalEnergyGuideBlock;
import net.crystalnexus.block.CrystalCrusherBlock;
import net.crystalnexus.block.CrystalAccepterBlock;
import net.crystalnexus.block.CrudeOilBlock;
import net.crystalnexus.block.CraftingFactoryBlock;
import net.crystalnexus.block.CopperNodeBlock;
import net.crystalnexus.block.ConveyerBeltOutputBlock;
import net.crystalnexus.block.ConveyerBeltInputBlock;
import net.crystalnexus.block.ConveyerBeltBlock;
import net.crystalnexus.block.ContainerBlock;
import net.crystalnexus.block.ConductiveEnergySplitterBlock;
import net.crystalnexus.block.ConductiveEnergyRefractorBlock;
import net.crystalnexus.block.ConductiveEnergyGuideBlock;
import net.crystalnexus.block.ComputationClusterBlock;
import net.crystalnexus.block.CircuitPressBlock;
import net.crystalnexus.block.ChlorophyteSmelterBlock;
import net.crystalnexus.block.ChlorophyteOreBlock;
import net.crystalnexus.block.ChlorophyteMachineFrameBlock;
import net.crystalnexus.block.ChlorophyteBlockBlock;
import net.crystalnexus.block.ChlorophyteAcceleratorBlock;
import net.crystalnexus.block.ChemicalReactionChamberBlock;
import net.crystalnexus.block.CarbonMachineFrameBlock;
import net.crystalnexus.block.CarbonGlassBlock;
import net.crystalnexus.block.CarbonBlockBlock;
import net.crystalnexus.block.BlutoniumOreBlock;
import net.crystalnexus.block.BlutoniumBlockBlock;
import net.crystalnexus.block.BluTNTBlock;
import net.crystalnexus.block.BlockPlacerBlock;
import net.crystalnexus.block.BiomaticSimulatorBlock;
import net.crystalnexus.block.BiomaticConstructorBlock;
import net.crystalnexus.block.BiomaticComposterBlock;
import net.crystalnexus.block.BatteryMonitorBlock;
import net.crystalnexus.block.BatteryBlock;
import net.crystalnexus.block.BasicEnergyCableBlock;
import net.crystalnexus.block.AncientDebrisNodeBlock;
import net.crystalnexus.block.AncientCrystalOreStoneBlock;
import net.crystalnexus.block.AncientCrystalOreBlock;
import net.crystalnexus.CrystalnexusMod;

public class CrystalnexusModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(CrystalnexusMod.MODID);
	public static final DeferredBlock<Block> CRYSTAL_PURIFIER = REGISTRY.register("crystal_purifier", CrystalPurifierBlock::new);
	public static final DeferredBlock<Block> CRYSTAL_ACCEPTER = REGISTRY.register("crystal_accepter", CrystalAccepterBlock::new);
	public static final DeferredBlock<Block> CRYSTALIZED_ALLOY_BLOCK = REGISTRY.register("crystalized_alloy_block", CrystalizedAlloyBlockBlock::new);
	public static final DeferredBlock<Block> CRYSTAL_CRUSHER = REGISTRY.register("crystal_crusher", CrystalCrusherBlock::new);
	public static final DeferredBlock<Block> ANCIENT_CRYSTAL_ORE = REGISTRY.register("ancient_crystal_ore", AncientCrystalOreBlock::new);
	public static final DeferredBlock<Block> DUST_SEPARATOR = REGISTRY.register("dust_separator", DustSeparatorBlock::new);
	public static final DeferredBlock<Block> CRYSTAL_GUIDE = REGISTRY.register("crystal_guide", CrystalGuideBlock::new);
	public static final DeferredBlock<Block> RAW_CRYSTAL_BLOCK = REGISTRY.register("raw_crystal_block", RawCrystalBlockBlock::new);
	public static final DeferredBlock<Block> ITEM_COLLECTOR = REGISTRY.register("item_collector", ItemCollectorBlock::new);
	public static final DeferredBlock<Block> EXTRACTINATOR = REGISTRY.register("extractinator", ExtractinatorBlock::new);
	public static final DeferredBlock<Block> CHLOROPHYTE_BLOCK = REGISTRY.register("chlorophyte_block", ChlorophyteBlockBlock::new);
	public static final DeferredBlock<Block> CRYSTAL_MACHINE_FRAME = REGISTRY.register("crystal_machine_frame", CrystalMachineFrameBlock::new);
	public static final DeferredBlock<Block> MACHINE_FRAME = REGISTRY.register("machine_frame", MachineFrameBlock::new);
	public static final DeferredBlock<Block> CHLOROPHYTE_MACHINE_FRAME = REGISTRY.register("chlorophyte_machine_frame", ChlorophyteMachineFrameBlock::new);
	public static final DeferredBlock<Block> CHLOROPHYTE_ACCELERATOR = REGISTRY.register("chlorophyte_accelerator", ChlorophyteAcceleratorBlock::new);
	public static final DeferredBlock<Block> BLUTONIUM_ORE = REGISTRY.register("blutonium_ore", BlutoniumOreBlock::new);
	public static final DeferredBlock<Block> INVERTIUM_MACHINE_FRAME = REGISTRY.register("invertium_machine_frame", InvertiumMachineFrameBlock::new);
	public static final DeferredBlock<Block> METALLURGIC_RECRYSTALLIZER = REGISTRY.register("metallurgic_recrystallizer", MetallurgicRecrystallizerBlock::new);
	public static final DeferredBlock<Block> INVERTIUM_BLOCK = REGISTRY.register("invertium_block", InvertiumBlockBlock::new);
	public static final DeferredBlock<Block> REACTOR_BLOCK = REGISTRY.register("reactor_block", ReactorBlockBlock::new);
	public static final DeferredBlock<Block> REACTOR_COMPUTER = REGISTRY.register("reactor_computer", ReactorComputerBlock::new);
	public static final DeferredBlock<Block> REACTOR_ENERGY_OUTPUT = REGISTRY.register("reactor_energy_output", ReactorEnergyOutputBlock::new);
	public static final DeferredBlock<Block> REACTOR_FLUID_INPUT = REGISTRY.register("reactor_fluid_input", ReactorFluidInputBlock::new);
	public static final DeferredBlock<Block> REACTOR_CORE = REGISTRY.register("reactor_core", ReactorCoreBlock::new);
	public static final DeferredBlock<Block> IRON_SMELTER = REGISTRY.register("iron_smelter", IronSmelterBlock::new);
	public static final DeferredBlock<Block> CRYSTAL_SMELTER = REGISTRY.register("crystal_smelter", CrystalSmelterBlock::new);
	public static final DeferredBlock<Block> INVERTIUM_SMELTER = REGISTRY.register("invertium_smelter", InvertiumSmelterBlock::new);
	public static final DeferredBlock<Block> CHLOROPHYTE_SMELTER = REGISTRY.register("chlorophyte_smelter", ChlorophyteSmelterBlock::new);
	public static final DeferredBlock<Block> TESSERACT = REGISTRY.register("tesseract", TesseractBlock::new);
	public static final DeferredBlock<Block> TESSERACT_OUTPUT = REGISTRY.register("tesseract_output", TesseractOutputBlock::new);
	public static final DeferredBlock<Block> CIRCUIT_PRESS = REGISTRY.register("circuit_press", CircuitPressBlock::new);
	public static final DeferredBlock<Block> BLU_TNT = REGISTRY.register("blu_tnt", BluTNTBlock::new);
	public static final DeferredBlock<Block> FACTORY_CONTROLLER = REGISTRY.register("factory_controller", FactoryControllerBlock::new);
	public static final DeferredBlock<Block> FACTORY_ITEM_CONTROLLER = REGISTRY.register("factory_item_controller", FactoryItemControllerBlock::new);
	public static final DeferredBlock<Block> FACTORY_OUTPUT_CONTROLLER = REGISTRY.register("factory_output_controller", FactoryOutputControllerBlock::new);
	public static final DeferredBlock<Block> INVERTER = REGISTRY.register("inverter", InverterBlock::new);
	public static final DeferredBlock<Block> REACTION_CHAMBER_BLOCK = REGISTRY.register("reaction_chamber_block", ReactionChamberBlockBlock::new);
	public static final DeferredBlock<Block> REACTION_CHAMBER_CORE = REGISTRY.register("reaction_chamber_core", ReactionChamberCoreBlock::new);
	public static final DeferredBlock<Block> REACTION_CHAMBER_COMPUTER = REGISTRY.register("reaction_chamber_computer", ReactionChamberComputerBlock::new);
	public static final DeferredBlock<Block> REACTION_ENERGY_INPUT = REGISTRY.register("reaction_energy_input", ReactionEnergyInputBlock::new);
	public static final DeferredBlock<Block> ULTIMA_SMELTER = REGISTRY.register("ultima_smelter", UltimaSmelterBlock::new);
	public static final DeferredBlock<Block> ENERGY_EXTRACTOR = REGISTRY.register("energy_extractor", EnergyExtractorBlock::new);
	public static final DeferredBlock<Block> CRYSTAL_ENERGY_GUIDE = REGISTRY.register("crystal_energy_guide", CrystalEnergyGuideBlock::new);
	public static final DeferredBlock<Block> ENERGY_REFRACTOR = REGISTRY.register("energy_refractor", EnergyRefractorBlock::new);
	public static final DeferredBlock<Block> ENERGY_SPLITTER = REGISTRY.register("energy_splitter", EnergySplitterBlock::new);
	public static final DeferredBlock<Block> MATTER_TRANSMUTATION_TABLE = REGISTRY.register("matter_transmutation_table", MatterTransmutationTableBlock::new);
	public static final DeferredBlock<Block> EE_MATTER_BLOCK = REGISTRY.register("ee_matter_block", EEMatterBlockBlock::new);
	public static final DeferredBlock<Block> BLOCK_PLACER = REGISTRY.register("block_placer", BlockPlacerBlock::new);
	public static final DeferredBlock<Block> SINGULARITY_COMPRESSOR = REGISTRY.register("singularity_compressor", SingularityCompressorBlock::new);
	public static final DeferredBlock<Block> ZERO_POINT = REGISTRY.register("zero_point", ZeroPointBlock::new);
	public static final DeferredBlock<Block> CARBON_GLASS = REGISTRY.register("carbon_glass", CarbonGlassBlock::new);
	public static final DeferredBlock<Block> CARBON_BLOCK = REGISTRY.register("carbon_block", CarbonBlockBlock::new);
	public static final DeferredBlock<Block> CARBON_MACHINE_FRAME = REGISTRY.register("carbon_machine_frame", CarbonMachineFrameBlock::new);
	public static final DeferredBlock<Block> CHEMICAL_REACTION_CHAMBER = REGISTRY.register("chemical_reaction_chamber", ChemicalReactionChamberBlock::new);
	public static final DeferredBlock<Block> CONTAINER = REGISTRY.register("container", ContainerBlock::new);
	public static final DeferredBlock<Block> POLYMER_BLOCK = REGISTRY.register("polymer_block", PolymerBlockBlock::new);
	public static final DeferredBlock<Block> CONDUCTIVE_ENERGY_GUIDE = REGISTRY.register("conductive_energy_guide", ConductiveEnergyGuideBlock::new);
	public static final DeferredBlock<Block> CONDUCTIVE_ENERGY_REFRACTOR = REGISTRY.register("conductive_energy_refractor", ConductiveEnergyRefractorBlock::new);
	public static final DeferredBlock<Block> CONDUCTIVE_ENERGY_SPLITTER = REGISTRY.register("conductive_energy_splitter", ConductiveEnergySplitterBlock::new);
	public static final DeferredBlock<Block> QUANTUM_MINER = REGISTRY.register("quantum_miner", QuantumMinerBlock::new);
	public static final DeferredBlock<Block> BATTERY = REGISTRY.register("battery", BatteryBlock::new);
	public static final DeferredBlock<Block> EE_BATTERY = REGISTRY.register("ee_battery", EEBatteryBlock::new);
	public static final DeferredBlock<Block> TURBINE = REGISTRY.register("turbine", TurbineBlock::new);
	public static final DeferredBlock<Block> MACHINEBLOCK = REGISTRY.register("machineblock", MachineblockBlock::new);
	public static final DeferredBlock<Block> ORE_PROCESSOR = REGISTRY.register("ore_processor", OreProcessorBlock::new);
	public static final DeferredBlock<Block> MACHINE_CORE = REGISTRY.register("machine_core", MachineCoreBlock::new);
	public static final DeferredBlock<Block> MACHINE_ENERGY_INPUT = REGISTRY.register("machine_energy_input", MachineEnergyInputBlock::new);
	public static final DeferredBlock<Block> RAW_CRYSTAL_BLOCK_SLAB = REGISTRY.register("raw_crystal_block_slab", RawCrystalBlockSlabBlock::new);
	public static final DeferredBlock<Block> RAW_CRYSTAL_BLOCK_STAIRS = REGISTRY.register("raw_crystal_block_stairs", RawCrystalBlockStairsBlock::new);
	public static final DeferredBlock<Block> BIOMATIC_COMPOSTER = REGISTRY.register("biomatic_composter", BiomaticComposterBlock::new);
	public static final DeferredBlock<Block> BIOMATIC_CONSTRUCTOR = REGISTRY.register("biomatic_constructor", BiomaticConstructorBlock::new);
	public static final DeferredBlock<Block> BIOMATIC_SIMULATOR = REGISTRY.register("biomatic_simulator", BiomaticSimulatorBlock::new);
	public static final DeferredBlock<Block> BATTERY_MONITOR = REGISTRY.register("battery_monitor", BatteryMonitorBlock::new);
	public static final DeferredBlock<Block> MULTIBLOCK_RESEARCH_STATION = REGISTRY.register("multiblock_research_station", MultiblockResearchStationBlock::new);
	public static final DeferredBlock<Block> ANCIENT_CRYSTAL_ORE_STONE = REGISTRY.register("ancient_crystal_ore_stone", AncientCrystalOreStoneBlock::new);
	public static final DeferredBlock<Block> CHLOROPHYTE_ORE = REGISTRY.register("chlorophyte_ore", ChlorophyteOreBlock::new);
	public static final DeferredBlock<Block> WARP_PAD = REGISTRY.register("warp_pad", WarpPadBlock::new);
	public static final DeferredBlock<Block> BLUTONIUM_BLOCK = REGISTRY.register("blutonium_block", BlutoniumBlockBlock::new);
	public static final DeferredBlock<Block> CRUDE_OIL = REGISTRY.register("crude_oil", CrudeOilBlock::new);
	public static final DeferredBlock<Block> GASOLINE = REGISTRY.register("gasoline", GasolineBlock::new);
	public static final DeferredBlock<Block> PISTON_GENERATOR = REGISTRY.register("piston_generator", PistonGeneratorBlock::new);
	public static final DeferredBlock<Block> INVERT_PISTON_GENERATOR = REGISTRY.register("invert_piston_generator", InvertPistonGeneratorBlock::new);
	public static final DeferredBlock<Block> RUBBER_BLOCK = REGISTRY.register("rubber_block", RubberBlockBlock::new);
	public static final DeferredBlock<Block> TARROCK = REGISTRY.register("tarrock", TarrockBlock::new);
	public static final DeferredBlock<Block> TARROCK_STAIRS = REGISTRY.register("tarrock_stairs", TarrockStairsBlock::new);
	public static final DeferredBlock<Block> TARROCK_SLAB = REGISTRY.register("tarrock_slab", TarrockSlabBlock::new);
	public static final DeferredBlock<Block> SILICON_ORE = REGISTRY.register("silicon_ore", SiliconOreBlock::new);
	public static final DeferredBlock<Block> TARROCK_SOIL = REGISTRY.register("tarrock_soil", TarrockSoilBlock::new);
	public static final DeferredBlock<Block> TARROCK_BRICKS = REGISTRY.register("tarrock_bricks", TarrockBricksBlock::new);
	public static final DeferredBlock<Block> TARROCK_BRICK_STAIRS = REGISTRY.register("tarrock_brick_stairs", TarrockBrickStairsBlock::new);
	public static final DeferredBlock<Block> TARROCK_BRICK_SLAB = REGISTRY.register("tarrock_brick_slab", TarrockBrickSlabBlock::new);
	public static final DeferredBlock<Block> TARROCK_WALL = REGISTRY.register("tarrock_wall", TarrockWallBlock::new);
	public static final DeferredBlock<Block> TARROCK_BRICK_WALL = REGISTRY.register("tarrock_brick_wall", TarrockBrickWallBlock::new);
	public static final DeferredBlock<Block> SMOOTH_TARROCK = REGISTRY.register("smooth_tarrock", SmoothTarrockBlock::new);
	public static final DeferredBlock<Block> SMOOTH_TARROCK_SLAB = REGISTRY.register("smooth_tarrock_slab", SmoothTarrockSlabBlock::new);
	public static final DeferredBlock<Block> SMOOTH_TARROCK_STAIRS = REGISTRY.register("smooth_tarrock_stairs", SmoothTarrockStairsBlock::new);
	public static final DeferredBlock<Block> SMOOTH_TARROCK_WALL = REGISTRY.register("smooth_tarrock_wall", SmoothTarrockWallBlock::new);
	public static final DeferredBlock<Block> TARROCK_BUTTON = REGISTRY.register("tarrock_button", TarrockButtonBlock::new);
	public static final DeferredBlock<Block> PIPE_STRAIGHT = REGISTRY.register("pipe_straight", PipeStraightBlock::new);
	public static final DeferredBlock<Block> PIPE_JUNCTION = REGISTRY.register("pipe_junction", PipeJunctionBlock::new);
	public static final DeferredBlock<Block> STEAM = REGISTRY.register("steam", SteamBlock::new);
	public static final DeferredBlock<Block> STEAM_COLLECTOR = REGISTRY.register("steam_collector", SteamCollectorBlock::new);
	public static final DeferredBlock<Block> STEAM_CHAMBER = REGISTRY.register("steam_chamber", SteamChamberBlock::new);
	public static final DeferredBlock<Block> CONVEYER_BELT = REGISTRY.register("conveyer_belt", ConveyerBeltBlock::new);
	public static final DeferredBlock<Block> CONVEYER_BELT_INPUT = REGISTRY.register("conveyer_belt_input", ConveyerBeltInputBlock::new);
	public static final DeferredBlock<Block> CONVEYER_BELT_OUTPUT = REGISTRY.register("conveyer_belt_output", ConveyerBeltOutputBlock::new);
	public static final DeferredBlock<Block> ITEM_ELEVATOR = REGISTRY.register("item_elevator", ItemElevatorBlock::new);
	public static final DeferredBlock<Block> ITEM_ELEVATOR_DOWN = REGISTRY.register("item_elevator_down", ItemElevatorDownBlock::new);
	public static final DeferredBlock<Block> CRAFTING_FACTORY = REGISTRY.register("crafting_factory", CraftingFactoryBlock::new);
	public static final DeferredBlock<Block> NODE_MINER = REGISTRY.register("node_miner", NodeMinerBlock::new);
	public static final DeferredBlock<Block> IRON_NODE = REGISTRY.register("iron_node", IronNodeBlock::new);
	public static final DeferredBlock<Block> GOLD_NODE = REGISTRY.register("gold_node", GoldNodeBlock::new);
	public static final DeferredBlock<Block> COPPER_NODE = REGISTRY.register("copper_node", CopperNodeBlock::new);
	public static final DeferredBlock<Block> STEAM_ENGINE = REGISTRY.register("steam_engine", SteamEngineBlock::new);
	public static final DeferredBlock<Block> STEAM_ENGINE_UPGRADE = REGISTRY.register("steam_engine_upgrade", SteamEngineUpgradeBlock::new);
	public static final DeferredBlock<Block> ANCIENT_DEBRIS_NODE = REGISTRY.register("ancient_debris_node", AncientDebrisNodeBlock::new);
	public static final DeferredBlock<Block> SINGULARITY_MATRIX = REGISTRY.register("singularity_matrix", SingularityMatrixBlock::new);
	public static final DeferredBlock<Block> DEPOT_UPLOADER = REGISTRY.register("depot_uploader", DepotUploaderBlock::new);
	public static final DeferredBlock<Block> DEPOT_DOWNLOADER = REGISTRY.register("depot_downloader", DepotDownloaderBlock::new);
	public static final DeferredBlock<Block> HYPER_MACHINE_FRAME = REGISTRY.register("hyper_machine_frame", HyperMachineFrameBlock::new);
	public static final DeferredBlock<Block> ENERGY_CABLE = REGISTRY.register("energy_cable", EnergyCableBlock::new);
	public static final DeferredBlock<Block> REACTOR_WASTE_OUTPUT = REGISTRY.register("reactor_waste_output", ReactorWasteOutputBlock::new);
	public static final DeferredBlock<Block> ENERGY_CABLE_MK_2 = REGISTRY.register("energy_cable_mk_2", EnergyCableMk2Block::new);
	public static final DeferredBlock<Block> BASIC_ENERGY_CABLE = REGISTRY.register("basic_energy_cable", BasicEnergyCableBlock::new);
	public static final DeferredBlock<Block> OIL_NODE = REGISTRY.register("oil_node", OilNodeBlock::new);
	public static final DeferredBlock<Block> LAVA_NODE = REGISTRY.register("lava_node", LavaNodeBlock::new);
	public static final DeferredBlock<Block> NODE_EXTRACTOR = REGISTRY.register("node_extractor", NodeExtractorBlock::new);
	public static final DeferredBlock<Block> TANK = REGISTRY.register("tank", TankBlock::new);
	public static final DeferredBlock<Block> FLUID_PACKAGER = REGISTRY.register("fluid_packager", FluidPackagerBlock::new);
	public static final DeferredBlock<Block> SULFUR_ORE = REGISTRY.register("sulfur_ore", SulfurOreBlock::new);
	public static final DeferredBlock<Block> SMART_SPLITTER = REGISTRY.register("smart_splitter", SmartSplitterBlock::new);
	public static final DeferredBlock<Block> COMPUTATION_CLUSTER = REGISTRY.register("computation_cluster", ComputationClusterBlock::new);
	// Start of user code block custom blocks
	// End of user code block custom blocks
}