/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.crystalnexus.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.crystalnexus.item.inventory.DepotUplinkInventoryCapability;
import net.crystalnexus.item.ZeroPointCoreItem;
import net.crystalnexus.item.YellowPaintballItem;
import net.crystalnexus.item.WhitePaintballItem;
import net.crystalnexus.item.UnstableEEMatterItem;
import net.crystalnexus.item.UltimateCrystalItem;
import net.crystalnexus.item.TurbineBladeItem;
import net.crystalnexus.item.SyntheticRubberItem;
import net.crystalnexus.item.StableCrystalItem;
import net.crystalnexus.item.SiliconItem;
import net.crystalnexus.item.RegulatedCrystalItem;
import net.crystalnexus.item.RedstoneSingularityItem;
import net.crystalnexus.item.RedPaintballItem;
import net.crystalnexus.item.ReactorUpgradePermafrostItem;
import net.crystalnexus.item.ReactorUpgradeItem;
import net.crystalnexus.item.RawChlorophyteItem;
import net.crystalnexus.item.RawCarbonItem;
import net.crystalnexus.item.RawBlutoniumItem;
import net.crystalnexus.item.RawAncientCrystalItem;
import net.crystalnexus.item.RangeUpgradeItem;
import net.crystalnexus.item.QuartzSingularityItem;
import net.crystalnexus.item.PurplePaintballItem;
import net.crystalnexus.item.PureBlutoniumItem;
import net.crystalnexus.item.PolymerSwordItem;
import net.crystalnexus.item.PolymerShovelItem;
import net.crystalnexus.item.PolymerSheetItem;
import net.crystalnexus.item.PolymerPickaxeItem;
import net.crystalnexus.item.PolymerHoeItem;
import net.crystalnexus.item.PolymerAxeItem;
import net.crystalnexus.item.PolyacrylonitrileDustItem;
import net.crystalnexus.item.PinkPaintballItem;
import net.crystalnexus.item.PaintballPlaceholderItem;
import net.crystalnexus.item.PaintGunItem;
import net.crystalnexus.item.OrangePaintballItem;
import net.crystalnexus.item.OmegaChipItem;
import net.crystalnexus.item.OilFuelCellItem;
import net.crystalnexus.item.NitrileItem;
import net.crystalnexus.item.NetheriteScrapPelletItem;
import net.crystalnexus.item.NetheriteScrapDustItem;
import net.crystalnexus.item.MiningLaserItem;
import net.crystalnexus.item.MagentaPaintballItem;
import net.crystalnexus.item.MachineBoltItem;
import net.crystalnexus.item.LinkCardItem;
import net.crystalnexus.item.LimePaintballItem;
import net.crystalnexus.item.LightGrayPaintballItem;
import net.crystalnexus.item.LightBluePaintballItem;
import net.crystalnexus.item.JetPackItem;
import net.crystalnexus.item.IronSingularityItem;
import net.crystalnexus.item.IronMachineBoltItem;
import net.crystalnexus.item.InvertiumSwordItem;
import net.crystalnexus.item.InvertiumShovelItem;
import net.crystalnexus.item.InvertiumPickaxeItem;
import net.crystalnexus.item.InvertiumNuggetItem;
import net.crystalnexus.item.InvertiumIngotItem;
import net.crystalnexus.item.InvertiumHoeItem;
import net.crystalnexus.item.InvertiumCrystalItem;
import net.crystalnexus.item.InvertiumAxeItem;
import net.crystalnexus.item.GreenPaintballItem;
import net.crystalnexus.item.GrayPaintballItem;
import net.crystalnexus.item.GoldSingularityItem;
import net.crystalnexus.item.GodlikeCrystalItem;
import net.crystalnexus.item.GasolineItem;
import net.crystalnexus.item.GasFuelCellItem;
import net.crystalnexus.item.FlorathaneWandItem;
import net.crystalnexus.item.FlorathaneItem;
import net.crystalnexus.item.FlamethrowerItem;
import net.crystalnexus.item.FertilizerItem;
import net.crystalnexus.item.FEPlaceholderItem;
import net.crystalnexus.item.EnergySingularityItem;
import net.crystalnexus.item.EnergizedSiliconItem;
import net.crystalnexus.item.EmptyFuelCellItem;
import net.crystalnexus.item.EfficiencyUpgradeItem;
import net.crystalnexus.item.EEMatterItem;
import net.crystalnexus.item.DragonCrystalItem;
import net.crystalnexus.item.DiamondSingularityItem;
import net.crystalnexus.item.DestabilizedCrystalItem;
import net.crystalnexus.item.DepotUplinkItem;
import net.crystalnexus.item.DepotStorageUpgradeItem;
import net.crystalnexus.item.CystalizedSwordItem;
import net.crystalnexus.item.CystalizedShovelItem;
import net.crystalnexus.item.CystalizedPickaxeItem;
import net.crystalnexus.item.CystalizedHoeItem;
import net.crystalnexus.item.CystalizedAxeItem;
import net.crystalnexus.item.CystalizedAlloyItem;
import net.crystalnexus.item.CyanPaintballItem;
import net.crystalnexus.item.CrystalizedAlloyMagnetItem;
import net.crystalnexus.item.CrystalExtractorItem;
import net.crystalnexus.item.CrystalAlloyNuggetItem;
import net.crystalnexus.item.CrudeOilItem;
import net.crystalnexus.item.CopperSingularityItem;
import net.crystalnexus.item.ControlledCrystalItem;
import net.crystalnexus.item.ConductiveAlloyItem;
import net.crystalnexus.item.CompoundSwordItem;
import net.crystalnexus.item.CompoundPickaxeItem;
import net.crystalnexus.item.CompoundEItem;
import net.crystalnexus.item.CoffeeItem;
import net.crystalnexus.item.CoalSingularityItem;
import net.crystalnexus.item.ChlorophyteSwordItem;
import net.crystalnexus.item.ChlorophyteShovelItem;
import net.crystalnexus.item.ChlorophytePickaxeItem;
import net.crystalnexus.item.ChlorophyteNuggetItem;
import net.crystalnexus.item.ChlorophyteIngotItem;
import net.crystalnexus.item.ChlorophyteHoeItem;
import net.crystalnexus.item.ChlorophyteDustItem;
import net.crystalnexus.item.ChlorophyteAxeItem;
import net.crystalnexus.item.CarbonRangeUpgradeItem;
import net.crystalnexus.item.CarbonJetpackItem;
import net.crystalnexus.item.CarbonItem;
import net.crystalnexus.item.CarbonFiberRodItem;
import net.crystalnexus.item.CarbonFiberItem;
import net.crystalnexus.item.CarbonEfficiencyUpgradeItem;
import net.crystalnexus.item.CarbonChipItem;
import net.crystalnexus.item.CarbonAccelerationUpgradeItem;
import net.crystalnexus.item.BlutoniumWasteItem;
import net.crystalnexus.item.BlutoniumNuggetItem;
import net.crystalnexus.item.BlutoniumIngotItem;
import net.crystalnexus.item.BlutoniumDustItem;
import net.crystalnexus.item.BlutoniumCrystalItem;
import net.crystalnexus.item.BluePaintballItem;
import net.crystalnexus.item.BlankChipItem;
import net.crystalnexus.item.BlackPaintballItem;
import net.crystalnexus.item.BiomassItem;
import net.crystalnexus.item.AtomicCoffeeItem;
import net.crystalnexus.item.AccelerationUpgradeItem;
import net.crystalnexus.CrystalnexusMod;

@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD)
public class CrystalnexusModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(CrystalnexusMod.MODID);
	public static final DeferredItem<Item> CRYSTAL_EXTRACTOR = REGISTRY.register("crystal_extractor", CrystalExtractorItem::new);
	public static final DeferredItem<Item> DESTABILIZED_CRYSTAL = REGISTRY.register("destabilized_crystal", DestabilizedCrystalItem::new);
	public static final DeferredItem<Item> DRAGON_CRYSTAL = REGISTRY.register("dragon_crystal", DragonCrystalItem::new);
	public static final DeferredItem<Item> CRYSTAL_PURIFIER = block(CrystalnexusModBlocks.CRYSTAL_PURIFIER);
	public static final DeferredItem<Item> STABLE_CRYSTAL = REGISTRY.register("stable_crystal", StableCrystalItem::new);
	public static final DeferredItem<Item> CRYSTAL_ACCEPTER = block(CrystalnexusModBlocks.CRYSTAL_ACCEPTER);
	public static final DeferredItem<Item> CONTROLLED_CRYSTAL = REGISTRY.register("controlled_crystal", ControlledCrystalItem::new);
	public static final DeferredItem<Item> REGULATED_CRYSTAL = REGISTRY.register("regulated_crystal", RegulatedCrystalItem::new);
	public static final DeferredItem<Item> ULTIMATE_CRYSTAL = REGISTRY.register("ultimate_crystal", UltimateCrystalItem::new);
	public static final DeferredItem<Item> RANGE_UPGRADE = REGISTRY.register("range_upgrade", RangeUpgradeItem::new);
	public static final DeferredItem<Item> CRYSTALIZED_ALLOY = REGISTRY.register("crystalized_alloy", CystalizedAlloyItem::new);
	public static final DeferredItem<Item> CRYSTALIZED_ALLOY_BLOCK = block(CrystalnexusModBlocks.CRYSTALIZED_ALLOY_BLOCK);
	public static final DeferredItem<Item> CRYSTAL_CRUSHER = block(CrystalnexusModBlocks.CRYSTAL_CRUSHER);
	public static final DeferredItem<Item> ACCELERATION_UPGRADE = REGISTRY.register("acceleration_upgrade", AccelerationUpgradeItem::new);
	public static final DeferredItem<Item> EFFICIENCY_UPGRADE = REGISTRY.register("efficiency_upgrade", EfficiencyUpgradeItem::new);
	public static final DeferredItem<Item> ANCIENT_CRYSTAL_ORE = block(CrystalnexusModBlocks.ANCIENT_CRYSTAL_ORE);
	public static final DeferredItem<Item> ANCIENT_CRYSTAL = REGISTRY.register("ancient_crystal", RawAncientCrystalItem::new);
	public static final DeferredItem<Item> DUST_SEPARATOR = block(CrystalnexusModBlocks.DUST_SEPARATOR);
	public static final DeferredItem<Item> CRYSTAL_GUIDE = block(CrystalnexusModBlocks.CRYSTAL_GUIDE);
	public static final DeferredItem<Item> RAW_CRYSTAL_BLOCK = block(CrystalnexusModBlocks.RAW_CRYSTAL_BLOCK);
	public static final DeferredItem<Item> ITEM_COLLECTOR = block(CrystalnexusModBlocks.ITEM_COLLECTOR);
	public static final DeferredItem<Item> CRYSTALIZED_ALLOY_MAGNET = REGISTRY.register("crystalized_alloy_magnet", CrystalizedAlloyMagnetItem::new);
	public static final DeferredItem<Item> EXTRACTINATOR = block(CrystalnexusModBlocks.EXTRACTINATOR);
	public static final DeferredItem<Item> CHLOROPHYTE_INGOT = REGISTRY.register("chlorophyte_ingot", ChlorophyteIngotItem::new);
	public static final DeferredItem<Item> CHLOROPHYTE_BLOCK = block(CrystalnexusModBlocks.CHLOROPHYTE_BLOCK);
	public static final DeferredItem<Item> CHLOROPHYTE_PICKAXE = REGISTRY.register("chlorophyte_pickaxe", ChlorophytePickaxeItem::new);
	public static final DeferredItem<Item> CHLOROPHYTE_AXE = REGISTRY.register("chlorophyte_axe", ChlorophyteAxeItem::new);
	public static final DeferredItem<Item> CHLOROPHYTE_SWORD = REGISTRY.register("chlorophyte_sword", ChlorophyteSwordItem::new);
	public static final DeferredItem<Item> CHLOROPHYTE_SHOVEL = REGISTRY.register("chlorophyte_shovel", ChlorophyteShovelItem::new);
	public static final DeferredItem<Item> CHLOROPHYTE_HOE = REGISTRY.register("chlorophyte_hoe", ChlorophyteHoeItem::new);
	public static final DeferredItem<Item> CYSTALIZED_PICKAXE = REGISTRY.register("cystalized_pickaxe", CystalizedPickaxeItem::new);
	public static final DeferredItem<Item> CYSTALIZED_AXE = REGISTRY.register("cystalized_axe", CystalizedAxeItem::new);
	public static final DeferredItem<Item> CYSTALIZED_SWORD = REGISTRY.register("cystalized_sword", CystalizedSwordItem::new);
	public static final DeferredItem<Item> CYSTALIZED_SHOVEL = REGISTRY.register("cystalized_shovel", CystalizedShovelItem::new);
	public static final DeferredItem<Item> CYSTALIZED_HOE = REGISTRY.register("cystalized_hoe", CystalizedHoeItem::new);
	public static final DeferredItem<Item> CRYSTAL_MACHINE_FRAME = block(CrystalnexusModBlocks.CRYSTAL_MACHINE_FRAME);
	public static final DeferredItem<Item> MACHINE_FRAME = block(CrystalnexusModBlocks.MACHINE_FRAME);
	public static final DeferredItem<Item> CHLOROPHYTE_MACHINE_FRAME = block(CrystalnexusModBlocks.CHLOROPHYTE_MACHINE_FRAME);
	public static final DeferredItem<Item> CHLOROPHYTE_ACCELERATOR = block(CrystalnexusModBlocks.CHLOROPHYTE_ACCELERATOR);
	public static final DeferredItem<Item> CHLOROPHYTE_NUGGET = REGISTRY.register("chlorophyte_nugget", ChlorophyteNuggetItem::new);
	public static final DeferredItem<Item> CRYSTAL_ALLOY_NUGGET = REGISTRY.register("crystal_alloy_nugget", CrystalAlloyNuggetItem::new);
	public static final DeferredItem<Item> BLUTONIUM_INGOT = REGISTRY.register("blutonium_ingot", BlutoniumIngotItem::new);
	public static final DeferredItem<Item> BLUTONIUM_CRYSTAL = REGISTRY.register("blutonium_crystal", BlutoniumCrystalItem::new);
	public static final DeferredItem<Item> RAW_BLUTONIUM = REGISTRY.register("raw_blutonium", RawBlutoniumItem::new);
	public static final DeferredItem<Item> BLUTONIUM_ORE = block(CrystalnexusModBlocks.BLUTONIUM_ORE);
	public static final DeferredItem<Item> INVERTIUM_INGOT = REGISTRY.register("invertium_ingot", InvertiumIngotItem::new);
	public static final DeferredItem<Item> INVERTIUM_MACHINE_FRAME = block(CrystalnexusModBlocks.INVERTIUM_MACHINE_FRAME);
	public static final DeferredItem<Item> METALLURGIC_RECRYSTALLIZER = block(CrystalnexusModBlocks.METALLURGIC_RECRYSTALLIZER, new Item.Properties().rarity(Rarity.EPIC));
	public static final DeferredItem<Item> INVERTIUM_CRYSTAL = REGISTRY.register("invertium_crystal", InvertiumCrystalItem::new);
	public static final DeferredItem<Item> INVERTIUM_NUGGET = REGISTRY.register("invertium_nugget", InvertiumNuggetItem::new);
	public static final DeferredItem<Item> INVERTIUM_BLOCK = block(CrystalnexusModBlocks.INVERTIUM_BLOCK);
	public static final DeferredItem<Item> REACTOR_BLOCK = block(CrystalnexusModBlocks.REACTOR_BLOCK);
	public static final DeferredItem<Item> REACTOR_COMPUTER = block(CrystalnexusModBlocks.REACTOR_COMPUTER);
	public static final DeferredItem<Item> REACTOR_ENERGY_OUTPUT = block(CrystalnexusModBlocks.REACTOR_ENERGY_OUTPUT);
	public static final DeferredItem<Item> REACTOR_FLUID_INPUT = block(CrystalnexusModBlocks.REACTOR_FLUID_INPUT);
	public static final DeferredItem<Item> REACTOR_CORE = block(CrystalnexusModBlocks.REACTOR_CORE);
	public static final DeferredItem<Item> IRON_SMELTER = block(CrystalnexusModBlocks.IRON_SMELTER);
	public static final DeferredItem<Item> CRYSTAL_SMELTER = block(CrystalnexusModBlocks.CRYSTAL_SMELTER);
	public static final DeferredItem<Item> INVERTIUM_SMELTER = block(CrystalnexusModBlocks.INVERTIUM_SMELTER);
	public static final DeferredItem<Item> CHLOROPHYTE_SMELTER = block(CrystalnexusModBlocks.CHLOROPHYTE_SMELTER);
	public static final DeferredItem<Item> TESSERACT = block(CrystalnexusModBlocks.TESSERACT);
	public static final DeferredItem<Item> LINK_CARD = REGISTRY.register("link_card", LinkCardItem::new);
	public static final DeferredItem<Item> TESSERACT_OUTPUT = block(CrystalnexusModBlocks.TESSERACT_OUTPUT);
	public static final DeferredItem<Item> BLANK_CHIP = REGISTRY.register("blank_chip", BlankChipItem::new);
	public static final DeferredItem<Item> CIRCUIT_PRESS = block(CrystalnexusModBlocks.CIRCUIT_PRESS);
	public static final DeferredItem<Item> BLU_TNT = block(CrystalnexusModBlocks.BLU_TNT);
	public static final DeferredItem<Item> FACTORY_CONTROLLER = block(CrystalnexusModBlocks.FACTORY_CONTROLLER);
	public static final DeferredItem<Item> FACTORY_ITEM_CONTROLLER = block(CrystalnexusModBlocks.FACTORY_ITEM_CONTROLLER);
	public static final DeferredItem<Item> FACTORY_OUTPUT_CONTROLLER = block(CrystalnexusModBlocks.FACTORY_OUTPUT_CONTROLLER);
	public static final DeferredItem<Item> INVERTER = block(CrystalnexusModBlocks.INVERTER);
	public static final DeferredItem<Item> EE_MATTER = REGISTRY.register("ee_matter", EEMatterItem::new);
	public static final DeferredItem<Item> REACTION_CHAMBER_BLOCK = block(CrystalnexusModBlocks.REACTION_CHAMBER_BLOCK);
	public static final DeferredItem<Item> REACTION_CHAMBER_CORE = block(CrystalnexusModBlocks.REACTION_CHAMBER_CORE);
	public static final DeferredItem<Item> REACTION_CHAMBER_COMPUTER = block(CrystalnexusModBlocks.REACTION_CHAMBER_COMPUTER);
	public static final DeferredItem<Item> REACTION_ENERGY_INPUT = block(CrystalnexusModBlocks.REACTION_ENERGY_INPUT);
	public static final DeferredItem<Item> FE_PLACEHOLDER = REGISTRY.register("fe_placeholder", FEPlaceholderItem::new);
	public static final DeferredItem<Item> RAW_CARBON = REGISTRY.register("raw_carbon", RawCarbonItem::new);
	public static final DeferredItem<Item> CARBON_FIBER = REGISTRY.register("carbon_fiber", CarbonFiberItem::new);
	public static final DeferredItem<Item> CARBON_FIBER_ROD = REGISTRY.register("carbon_fiber_rod", CarbonFiberRodItem::new);
	public static final DeferredItem<Item> COMPOUND_E = REGISTRY.register("compound_e", CompoundEItem::new);
	public static final DeferredItem<Item> COMPOUND_PICKAXE = REGISTRY.register("compound_pickaxe", CompoundPickaxeItem::new);
	public static final DeferredItem<Item> UNSTABLE_EE_MATTER = REGISTRY.register("unstable_ee_matter", UnstableEEMatterItem::new);
	public static final DeferredItem<Item> ULTIMA_SMELTER = block(CrystalnexusModBlocks.ULTIMA_SMELTER);
	public static final DeferredItem<Item> COMPOUND_SWORD = REGISTRY.register("compound_sword", CompoundSwordItem::new);
	public static final DeferredItem<Item> ENERGY_EXTRACTOR = block(CrystalnexusModBlocks.ENERGY_EXTRACTOR);
	public static final DeferredItem<Item> CRYSTAL_ENERGY_GUIDE = block(CrystalnexusModBlocks.CRYSTAL_ENERGY_GUIDE);
	public static final DeferredItem<Item> ENERGY_REFRACTOR = block(CrystalnexusModBlocks.ENERGY_REFRACTOR);
	public static final DeferredItem<Item> ENERGY_SPLITTER = block(CrystalnexusModBlocks.ENERGY_SPLITTER);
	public static final DeferredItem<Item> MATTER_TRANSMUTATION_TABLE = block(CrystalnexusModBlocks.MATTER_TRANSMUTATION_TABLE);
	public static final DeferredItem<Item> GODLIKE_CRYSTAL = REGISTRY.register("godlike_crystal", GodlikeCrystalItem::new);
	public static final DeferredItem<Item> EE_MATTER_BLOCK = block(CrystalnexusModBlocks.EE_MATTER_BLOCK);
	public static final DeferredItem<Item> BLOCK_PLACER = block(CrystalnexusModBlocks.BLOCK_PLACER);
	public static final DeferredItem<Item> SINGULARITY_COMPRESSOR = block(CrystalnexusModBlocks.SINGULARITY_COMPRESSOR);
	public static final DeferredItem<Item> REACTOR_UPGRADE = REGISTRY.register("reactor_upgrade", ReactorUpgradeItem::new);
	public static final DeferredItem<Item> IRON_SINGULARITY = REGISTRY.register("iron_singularity", IronSingularityItem::new);
	public static final DeferredItem<Item> DIAMOND_SINGULARITY = REGISTRY.register("diamond_singularity", DiamondSingularityItem::new);
	public static final DeferredItem<Item> ZERO_POINT = block(CrystalnexusModBlocks.ZERO_POINT, new Item.Properties().rarity(Rarity.EPIC));
	public static final DeferredItem<Item> CARBON_GLASS = block(CrystalnexusModBlocks.CARBON_GLASS);
	public static final DeferredItem<Item> GOLD_SINGULARITY = REGISTRY.register("gold_singularity", GoldSingularityItem::new);
	public static final DeferredItem<Item> COPPER_SINGULARITY = REGISTRY.register("copper_singularity", CopperSingularityItem::new);
	public static final DeferredItem<Item> REDSTONE_SINGULARITY = REGISTRY.register("redstone_singularity", RedstoneSingularityItem::new);
	public static final DeferredItem<Item> QUARTZ_SINGULARITY = REGISTRY.register("quartz_singularity", QuartzSingularityItem::new);
	public static final DeferredItem<Item> COAL_SINGULARITY = REGISTRY.register("coal_singularity", CoalSingularityItem::new);
	public static final DeferredItem<Item> CARBON_RANGE_UPGRADE = REGISTRY.register("carbon_range_upgrade", CarbonRangeUpgradeItem::new);
	public static final DeferredItem<Item> CARBON_ACCELERATION_UPGRADE = REGISTRY.register("carbon_acceleration_upgrade", CarbonAccelerationUpgradeItem::new);
	public static final DeferredItem<Item> CARBON_EFFICIENCY_UPGRADE = REGISTRY.register("carbon_efficiency_upgrade", CarbonEfficiencyUpgradeItem::new);
	public static final DeferredItem<Item> CARBON_CHIP = REGISTRY.register("carbon_chip", CarbonChipItem::new);
	public static final DeferredItem<Item> CARBON_BLOCK = block(CrystalnexusModBlocks.CARBON_BLOCK);
	public static final DeferredItem<Item> CARBON_MACHINE_FRAME = block(CrystalnexusModBlocks.CARBON_MACHINE_FRAME);
	public static final DeferredItem<Item> CHEMICAL_REACTION_CHAMBER = block(CrystalnexusModBlocks.CHEMICAL_REACTION_CHAMBER);
	public static final DeferredItem<Item> NITRILE = REGISTRY.register("nitrile", NitrileItem::new);
	public static final DeferredItem<Item> POLYACRYLONITRILE_DUST = REGISTRY.register("polyacrylonitrile_dust", PolyacrylonitrileDustItem::new);
	public static final DeferredItem<Item> POLYMER_SHEET = REGISTRY.register("polymer_sheet", PolymerSheetItem::new);
	public static final DeferredItem<Item> CONTAINER = block(CrystalnexusModBlocks.CONTAINER, new Item.Properties().stacksTo(1));
	public static final DeferredItem<Item> REACTOR_UPGRADE_PERMAFROST = REGISTRY.register("reactor_upgrade_permafrost", ReactorUpgradePermafrostItem::new);
	public static final DeferredItem<Item> FLORATHANE = REGISTRY.register("florathane", FlorathaneItem::new);
	public static final DeferredItem<Item> FERTILIZER = REGISTRY.register("fertilizer", FertilizerItem::new);
	public static final DeferredItem<Item> FLORATHANE_WAND = REGISTRY.register("florathane_wand", FlorathaneWandItem::new);
	public static final DeferredItem<Item> POLYMER_PICKAXE = REGISTRY.register("polymer_pickaxe", PolymerPickaxeItem::new);
	public static final DeferredItem<Item> POLYMER_AXE = REGISTRY.register("polymer_axe", PolymerAxeItem::new);
	public static final DeferredItem<Item> POLYMER_SWORD = REGISTRY.register("polymer_sword", PolymerSwordItem::new);
	public static final DeferredItem<Item> POLYMER_SHOVEL = REGISTRY.register("polymer_shovel", PolymerShovelItem::new);
	public static final DeferredItem<Item> POLYMER_HOE = REGISTRY.register("polymer_hoe", PolymerHoeItem::new);
	public static final DeferredItem<Item> POLYMER_BLOCK = block(CrystalnexusModBlocks.POLYMER_BLOCK);
	public static final DeferredItem<Item> CONDUCTIVE_ALLOY = REGISTRY.register("conductive_alloy", ConductiveAlloyItem::new);
	public static final DeferredItem<Item> CONDUCTIVE_ENERGY_GUIDE = block(CrystalnexusModBlocks.CONDUCTIVE_ENERGY_GUIDE);
	public static final DeferredItem<Item> CONDUCTIVE_ENERGY_REFRACTOR = block(CrystalnexusModBlocks.CONDUCTIVE_ENERGY_REFRACTOR);
	public static final DeferredItem<Item> CONDUCTIVE_ENERGY_SPLITTER = block(CrystalnexusModBlocks.CONDUCTIVE_ENERGY_SPLITTER);
	public static final DeferredItem<Item> QUANTUM_MINER = block(CrystalnexusModBlocks.QUANTUM_MINER);
	public static final DeferredItem<Item> FLAMETHROWER = REGISTRY.register("flamethrower", FlamethrowerItem::new);
	public static final DeferredItem<Item> BATTERY = block(CrystalnexusModBlocks.BATTERY);
	public static final DeferredItem<Item> EE_BATTERY = block(CrystalnexusModBlocks.EE_BATTERY);
	public static final DeferredItem<Item> PAINT_GUN = REGISTRY.register("paint_gun", PaintGunItem::new);
	public static final DeferredItem<Item> WHITE_PAINTBALL = REGISTRY.register("white_paintball", WhitePaintballItem::new);
	public static final DeferredItem<Item> LIGHT_GRAY_PAINTBALL = REGISTRY.register("light_gray_paintball", LightGrayPaintballItem::new);
	public static final DeferredItem<Item> GRAY_PAINTBALL = REGISTRY.register("gray_paintball", GrayPaintballItem::new);
	public static final DeferredItem<Item> BLACK_PAINTBALL = REGISTRY.register("black_paintball", BlackPaintballItem::new);
	public static final DeferredItem<Item> RED_PAINTBALL = REGISTRY.register("red_paintball", RedPaintballItem::new);
	public static final DeferredItem<Item> ORANGE_PAINTBALL = REGISTRY.register("orange_paintball", OrangePaintballItem::new);
	public static final DeferredItem<Item> YELLOW_PAINTBALL = REGISTRY.register("yellow_paintball", YellowPaintballItem::new);
	public static final DeferredItem<Item> GREEN_PAINTBALL = REGISTRY.register("green_paintball", GreenPaintballItem::new);
	public static final DeferredItem<Item> LIME_PAINTBALL = REGISTRY.register("lime_paintball", LimePaintballItem::new);
	public static final DeferredItem<Item> CYAN_PAINTBALL = REGISTRY.register("cyan_paintball", CyanPaintballItem::new);
	public static final DeferredItem<Item> LIGHT_BLUE_PAINTBALL = REGISTRY.register("light_blue_paintball", LightBluePaintballItem::new);
	public static final DeferredItem<Item> BLUE_PAINTBALL = REGISTRY.register("blue_paintball", BluePaintballItem::new);
	public static final DeferredItem<Item> PURPLE_PAINTBALL = REGISTRY.register("purple_paintball", PurplePaintballItem::new);
	public static final DeferredItem<Item> MAGENTA_PAINTBALL = REGISTRY.register("magenta_paintball", MagentaPaintballItem::new);
	public static final DeferredItem<Item> PINK_PAINTBALL = REGISTRY.register("pink_paintball", PinkPaintballItem::new);
	public static final DeferredItem<Item> PAINTBALL_PLACEHOLDER = REGISTRY.register("paintball_placeholder", PaintballPlaceholderItem::new);
	public static final DeferredItem<Item> TURBINE = block(CrystalnexusModBlocks.TURBINE);
	public static final DeferredItem<Item> TURBINE_BLADE = REGISTRY.register("turbine_blade", TurbineBladeItem::new);
	public static final DeferredItem<Item> NETHERITE_SCRAP_DUST = REGISTRY.register("netherite_scrap_dust", NetheriteScrapDustItem::new);
	public static final DeferredItem<Item> MACHINEBLOCK = block(CrystalnexusModBlocks.MACHINEBLOCK);
	public static final DeferredItem<Item> ORE_PROCESSOR = block(CrystalnexusModBlocks.ORE_PROCESSOR);
	public static final DeferredItem<Item> MACHINE_CORE = block(CrystalnexusModBlocks.MACHINE_CORE);
	public static final DeferredItem<Item> MACHINE_ENERGY_INPUT = block(CrystalnexusModBlocks.MACHINE_ENERGY_INPUT);
	public static final DeferredItem<Item> ENERGY_SINGULARITY = REGISTRY.register("energy_singularity", EnergySingularityItem::new);
	public static final DeferredItem<Item> RAW_CRYSTAL_BLOCK_SLAB = block(CrystalnexusModBlocks.RAW_CRYSTAL_BLOCK_SLAB);
	public static final DeferredItem<Item> RAW_CRYSTAL_BLOCK_STAIRS = block(CrystalnexusModBlocks.RAW_CRYSTAL_BLOCK_STAIRS);
	public static final DeferredItem<Item> BIOMATIC_COMPOSTER = block(CrystalnexusModBlocks.BIOMATIC_COMPOSTER);
	public static final DeferredItem<Item> BIOMASS = REGISTRY.register("biomass", BiomassItem::new);
	public static final DeferredItem<Item> BIOMATIC_CONSTRUCTOR = block(CrystalnexusModBlocks.BIOMATIC_CONSTRUCTOR);
	public static final DeferredItem<Item> BIOMATIC_SIMULATOR = block(CrystalnexusModBlocks.BIOMATIC_SIMULATOR);
	public static final DeferredItem<Item> BATTERY_MONITOR = block(CrystalnexusModBlocks.BATTERY_MONITOR);
	public static final DeferredItem<Item> INVERTIUM_PICKAXE = REGISTRY.register("invertium_pickaxe", InvertiumPickaxeItem::new);
	public static final DeferredItem<Item> INVERTIUM_AXE = REGISTRY.register("invertium_axe", InvertiumAxeItem::new);
	public static final DeferredItem<Item> INVERTIUM_SWORD = REGISTRY.register("invertium_sword", InvertiumSwordItem::new);
	public static final DeferredItem<Item> INVERTIUM_SHOVEL = REGISTRY.register("invertium_shovel", InvertiumShovelItem::new);
	public static final DeferredItem<Item> INVERTIUM_HOE = REGISTRY.register("invertium_hoe", InvertiumHoeItem::new);
	public static final DeferredItem<Item> MULTIBLOCK_RESEARCH_STATION = block(CrystalnexusModBlocks.MULTIBLOCK_RESEARCH_STATION);
	public static final DeferredItem<Item> SILICON = REGISTRY.register("silicon", SiliconItem::new);
	public static final DeferredItem<Item> ENERGIZED_SILICON = REGISTRY.register("energized_silicon", EnergizedSiliconItem::new);
	public static final DeferredItem<Item> COFFEE = REGISTRY.register("coffee", CoffeeItem::new);
	public static final DeferredItem<Item> ATOMIC_COFFEE = REGISTRY.register("atomic_coffee", AtomicCoffeeItem::new);
	public static final DeferredItem<Item> ANCIENT_CRYSTAL_ORE_STONE = block(CrystalnexusModBlocks.ANCIENT_CRYSTAL_ORE_STONE);
	public static final DeferredItem<Item> CHLOROPHYTE_ORE = block(CrystalnexusModBlocks.CHLOROPHYTE_ORE);
	public static final DeferredItem<Item> RAW_CHLOROPHYTE = REGISTRY.register("raw_chlorophyte", RawChlorophyteItem::new);
	public static final DeferredItem<Item> CHLOROPHYTE_DUST = REGISTRY.register("chlorophyte_dust", ChlorophyteDustItem::new);
	public static final DeferredItem<Item> BLUTONIUM_DUST = REGISTRY.register("blutonium_dust", BlutoniumDustItem::new);
	public static final DeferredItem<Item> BLUTONIUM_NUGGET = REGISTRY.register("blutonium_nugget", BlutoniumNuggetItem::new);
	public static final DeferredItem<Item> WARP_PAD = block(CrystalnexusModBlocks.WARP_PAD, new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final DeferredItem<Item> BLUTONIUM_BLOCK = block(CrystalnexusModBlocks.BLUTONIUM_BLOCK);
	public static final DeferredItem<Item> CRUDE_OIL_BUCKET = REGISTRY.register("crude_oil_bucket", CrudeOilItem::new);
	public static final DeferredItem<Item> GASOLINE_BUCKET = REGISTRY.register("gasoline_bucket", GasolineItem::new);
	public static final DeferredItem<Item> EMPTY_FUEL_CELL = REGISTRY.register("empty_fuel_cell", EmptyFuelCellItem::new);
	public static final DeferredItem<Item> OIL_FUEL_CELL = REGISTRY.register("oil_fuel_cell", OilFuelCellItem::new);
	public static final DeferredItem<Item> GAS_FUEL_CELL = REGISTRY.register("gas_fuel_cell", GasFuelCellItem::new);
	public static final DeferredItem<Item> PISTON_GENERATOR = block(CrystalnexusModBlocks.PISTON_GENERATOR);
	public static final DeferredItem<Item> SYNTHETIC_RUBBER = REGISTRY.register("synthetic_rubber", SyntheticRubberItem::new);
	public static final DeferredItem<Item> INVERT_PISTON_GENERATOR = block(CrystalnexusModBlocks.INVERT_PISTON_GENERATOR);
	public static final DeferredItem<Item> RUBBER_BLOCK = block(CrystalnexusModBlocks.RUBBER_BLOCK);
	public static final DeferredItem<Item> TARROCK = block(CrystalnexusModBlocks.TARROCK);
	public static final DeferredItem<Item> TARROCK_STAIRS = block(CrystalnexusModBlocks.TARROCK_STAIRS);
	public static final DeferredItem<Item> TARROCK_SLAB = block(CrystalnexusModBlocks.TARROCK_SLAB);
	public static final DeferredItem<Item> SILICON_ORE = block(CrystalnexusModBlocks.SILICON_ORE);
	public static final DeferredItem<Item> TARROCK_SOIL = block(CrystalnexusModBlocks.TARROCK_SOIL);
	public static final DeferredItem<Item> TARROCK_BRICKS = block(CrystalnexusModBlocks.TARROCK_BRICKS);
	public static final DeferredItem<Item> TARROCK_BRICK_STAIRS = block(CrystalnexusModBlocks.TARROCK_BRICK_STAIRS);
	public static final DeferredItem<Item> TARROCK_BRICK_SLAB = block(CrystalnexusModBlocks.TARROCK_BRICK_SLAB);
	public static final DeferredItem<Item> TARROCK_WALL = block(CrystalnexusModBlocks.TARROCK_WALL);
	public static final DeferredItem<Item> TARROCK_BRICK_WALL = block(CrystalnexusModBlocks.TARROCK_BRICK_WALL);
	public static final DeferredItem<Item> SMOOTH_TARROCK = block(CrystalnexusModBlocks.SMOOTH_TARROCK);
	public static final DeferredItem<Item> SMOOTH_TARROCK_SLAB = block(CrystalnexusModBlocks.SMOOTH_TARROCK_SLAB);
	public static final DeferredItem<Item> SMOOTH_TARROCK_STAIRS = block(CrystalnexusModBlocks.SMOOTH_TARROCK_STAIRS);
	public static final DeferredItem<Item> SMOOTH_TARROCK_WALL = block(CrystalnexusModBlocks.SMOOTH_TARROCK_WALL);
	public static final DeferredItem<Item> TARROCK_BUTTON = block(CrystalnexusModBlocks.TARROCK_BUTTON);
	public static final DeferredItem<Item> JET_PACK_CHESTPLATE = REGISTRY.register("jet_pack_chestplate", JetPackItem.Chestplate::new);
	public static final DeferredItem<Item> CARBON_HELMET = REGISTRY.register("carbon_helmet", CarbonItem.Helmet::new);
	public static final DeferredItem<Item> CARBON_CHESTPLATE = REGISTRY.register("carbon_chestplate", CarbonItem.Chestplate::new);
	public static final DeferredItem<Item> CARBON_LEGGINGS = REGISTRY.register("carbon_leggings", CarbonItem.Leggings::new);
	public static final DeferredItem<Item> CARBON_BOOTS = REGISTRY.register("carbon_boots", CarbonItem.Boots::new);
	public static final DeferredItem<Item> CARBON_JETPACK_CHESTPLATE = REGISTRY.register("carbon_jetpack_chestplate", CarbonJetpackItem.Chestplate::new);
	public static final DeferredItem<Item> PIPE_STRAIGHT = block(CrystalnexusModBlocks.PIPE_STRAIGHT);
	public static final DeferredItem<Item> PIPE_JUNCTION = block(CrystalnexusModBlocks.PIPE_JUNCTION);
	public static final DeferredItem<Item> STEAM_COLLECTOR = block(CrystalnexusModBlocks.STEAM_COLLECTOR);
	public static final DeferredItem<Item> STEAM_CHAMBER = block(CrystalnexusModBlocks.STEAM_CHAMBER);
	public static final DeferredItem<Item> MINING_LASER = REGISTRY.register("mining_laser", MiningLaserItem::new);
	public static final DeferredItem<Item> CONVEYER_BELT = block(CrystalnexusModBlocks.CONVEYER_BELT);
	public static final DeferredItem<Item> CONVEYER_BELT_INPUT = block(CrystalnexusModBlocks.CONVEYER_BELT_INPUT);
	public static final DeferredItem<Item> CONVEYER_BELT_OUTPUT = block(CrystalnexusModBlocks.CONVEYER_BELT_OUTPUT);
	public static final DeferredItem<Item> ITEM_ELEVATOR = block(CrystalnexusModBlocks.ITEM_ELEVATOR);
	public static final DeferredItem<Item> ITEM_ELEVATOR_DOWN = block(CrystalnexusModBlocks.ITEM_ELEVATOR_DOWN);
	public static final DeferredItem<Item> CRAFTING_FACTORY = block(CrystalnexusModBlocks.CRAFTING_FACTORY);
	public static final DeferredItem<Item> MACHINE_BOLT = REGISTRY.register("machine_bolt", MachineBoltItem::new);
	public static final DeferredItem<Item> PURE_BLUTONIUM = REGISTRY.register("pure_blutonium", PureBlutoniumItem::new);
	public static final DeferredItem<Item> IRON_MACHINE_BOLT = REGISTRY.register("iron_machine_bolt", IronMachineBoltItem::new);
	public static final DeferredItem<Item> NODE_MINER = block(CrystalnexusModBlocks.NODE_MINER);
	public static final DeferredItem<Item> IRON_NODE = block(CrystalnexusModBlocks.IRON_NODE);
	public static final DeferredItem<Item> GOLD_NODE = block(CrystalnexusModBlocks.GOLD_NODE);
	public static final DeferredItem<Item> COPPER_NODE = block(CrystalnexusModBlocks.COPPER_NODE);
	public static final DeferredItem<Item> STEAM_ENGINE = block(CrystalnexusModBlocks.STEAM_ENGINE);
	public static final DeferredItem<Item> STEAM_ENGINE_UPGRADE = block(CrystalnexusModBlocks.STEAM_ENGINE_UPGRADE);
	public static final DeferredItem<Item> ANCIENT_DEBRIS_NODE = block(CrystalnexusModBlocks.ANCIENT_DEBRIS_NODE);
	public static final DeferredItem<Item> NETHERITE_SCRAP_PELLET = REGISTRY.register("netherite_scrap_pellet", NetheriteScrapPelletItem::new);
	public static final DeferredItem<Item> OMEGA_CHIP = REGISTRY.register("omega_chip", OmegaChipItem::new);
	public static final DeferredItem<Item> SINGULARITY_MATRIX = block(CrystalnexusModBlocks.SINGULARITY_MATRIX, new Item.Properties().rarity(Rarity.EPIC));
	public static final DeferredItem<Item> DEPOT_UPLINK = REGISTRY.register("depot_uplink", DepotUplinkItem::new);
	public static final DeferredItem<Item> DEPOT_UPLOADER = block(CrystalnexusModBlocks.DEPOT_UPLOADER);
	public static final DeferredItem<Item> DEPOT_DOWNLOADER = block(CrystalnexusModBlocks.DEPOT_DOWNLOADER);
	public static final DeferredItem<Item> HYPER_MACHINE_FRAME = block(CrystalnexusModBlocks.HYPER_MACHINE_FRAME);
	public static final DeferredItem<Item> ENERGY_CABLE = block(CrystalnexusModBlocks.ENERGY_CABLE);
	public static final DeferredItem<Item> BLUTONIUM_WASTE = REGISTRY.register("blutonium_waste", BlutoniumWasteItem::new);
	public static final DeferredItem<Item> REACTOR_WASTE_OUTPUT = block(CrystalnexusModBlocks.REACTOR_WASTE_OUTPUT);
	public static final DeferredItem<Item> DEPOT_STORAGE_UPGRADE = REGISTRY.register("depot_storage_upgrade", DepotStorageUpgradeItem::new);
	public static final DeferredItem<Item> ENERGY_CABLE_MK_2 = block(CrystalnexusModBlocks.ENERGY_CABLE_MK_2);
	public static final DeferredItem<Item> BASIC_ENERGY_CABLE = block(CrystalnexusModBlocks.BASIC_ENERGY_CABLE);
	public static final DeferredItem<Item> ZERO_POINT_CORE = REGISTRY.register("zero_point_core", ZeroPointCoreItem::new);
	public static final DeferredItem<Item> OIL_NODE = block(CrystalnexusModBlocks.OIL_NODE);
	public static final DeferredItem<Item> LAVA_NODE = block(CrystalnexusModBlocks.LAVA_NODE);
	public static final DeferredItem<Item> NODE_EXTRACTOR = block(CrystalnexusModBlocks.NODE_EXTRACTOR);
	public static final DeferredItem<Item> TANK = block(CrystalnexusModBlocks.TANK);
	public static final DeferredItem<Item> FLUID_PACKAGER = block(CrystalnexusModBlocks.FLUID_PACKAGER);

	// Start of user code block custom items
	// End of user code block custom items
	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new DepotUplinkInventoryCapability(stack), DEPOT_UPLINK.get());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ItemsClientSideHandler {
		@SubscribeEvent
		@OnlyIn(Dist.CLIENT)
		public static void clientLoad(FMLClientSetupEvent event) {
			event.enqueueWork(() -> {
				ItemProperties.register(FLORATHANE_WAND.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(FLAMETHROWER.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(MINING_LASER.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
			});
		}
	}
}