/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.crystalnexus.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.items.wrapper.SidedInvWrapper;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.WorldlyContainer;
import net.minecraft.core.registries.BuiltInRegistries;

import net.crystalnexus.block.entity.ZeroPointBlockEntity;
import net.crystalnexus.block.entity.WarpPadBlockEntity;
import net.crystalnexus.block.entity.UltimaSmelterBlockEntity;
import net.crystalnexus.block.entity.TurbineBlockEntity;
import net.crystalnexus.block.entity.TesseractOutputBlockEntity;
import net.crystalnexus.block.entity.TesseractBlockEntity;
import net.crystalnexus.block.entity.TankBlockEntity;
import net.crystalnexus.block.entity.SteamEngineUpgradeBlockEntity;
import net.crystalnexus.block.entity.SteamEngineBlockEntity;
import net.crystalnexus.block.entity.SteamCollectorBlockEntity;
import net.crystalnexus.block.entity.SteamChamberBlockEntity;
import net.crystalnexus.block.entity.SmartSplitterBlockEntity;
import net.crystalnexus.block.entity.SingularityMatrixBlockEntity;
import net.crystalnexus.block.entity.SingularityCompressorBlockEntity;
import net.crystalnexus.block.entity.ReactorWasteOutputBlockEntity;
import net.crystalnexus.block.entity.ReactorFluidInputBlockEntity;
import net.crystalnexus.block.entity.ReactorEnergyOutputBlockEntity;
import net.crystalnexus.block.entity.ReactorComputerBlockEntity;
import net.crystalnexus.block.entity.ReactionEnergyInputBlockEntity;
import net.crystalnexus.block.entity.ReactionChamberComputerBlockEntity;
import net.crystalnexus.block.entity.RadPlaceholderBlockEntity;
import net.crystalnexus.block.entity.QuarryBlockEntity;
import net.crystalnexus.block.entity.QuantumMinerBlockEntity;
import net.crystalnexus.block.entity.PistonGeneratorBlockEntity;
import net.crystalnexus.block.entity.PipeStraightBlockEntity;
import net.crystalnexus.block.entity.PipeJunctionBlockEntity;
import net.crystalnexus.block.entity.ParticleAcceleratorTubeBlockEntity;
import net.crystalnexus.block.entity.ParticleAcceleratorControllerBlockEntity;
import net.crystalnexus.block.entity.OreProcessorBlockEntity;
import net.crystalnexus.block.entity.NodeMinerBlockEntity;
import net.crystalnexus.block.entity.NodeExtractorBlockEntity;
import net.crystalnexus.block.entity.MultiblockResearchStationBlockEntity;
import net.crystalnexus.block.entity.MetallurgicRecrystallizerBlockEntity;
import net.crystalnexus.block.entity.MatterTransmutationTableBlockEntity;
import net.crystalnexus.block.entity.MachineblockBlockEntity;
import net.crystalnexus.block.entity.MachineEnergyInputBlockEntity;
import net.crystalnexus.block.entity.MachineCoreBlockEntity;
import net.crystalnexus.block.entity.ItemElevatorDownBlockEntity;
import net.crystalnexus.block.entity.ItemElevatorBlockEntity;
import net.crystalnexus.block.entity.ItemCollectorBlockEntity;
import net.crystalnexus.block.entity.IronSmelterBlockEntity;
import net.crystalnexus.block.entity.InvertiumSmelterBlockEntity;
import net.crystalnexus.block.entity.InverterBlockEntity;
import net.crystalnexus.block.entity.InvertPistonGeneratorBlockEntity;
import net.crystalnexus.block.entity.FluidPackagerBlockEntity;
import net.crystalnexus.block.entity.FactoryOutputControllerBlockEntity;
import net.crystalnexus.block.entity.FactoryItemControllerBlockEntity;
import net.crystalnexus.block.entity.FactoryControllerBlockEntity;
import net.crystalnexus.block.entity.ExtractinatorBlockEntity;
import net.crystalnexus.block.entity.EnergySplitterBlockEntity;
import net.crystalnexus.block.entity.EnergyRefractorBlockEntity;
import net.crystalnexus.block.entity.EnergyExtractorBlockEntity;
import net.crystalnexus.block.entity.EnergyCableMk2BlockEntity;
import net.crystalnexus.block.entity.EnergyCableBlockEntity;
import net.crystalnexus.block.entity.ElectromagnetBlockEntity;
import net.crystalnexus.block.entity.EEBatteryBlockEntity;
import net.crystalnexus.block.entity.DustSeparatorBlockEntity;
import net.crystalnexus.block.entity.DepotUploaderBlockEntity;
import net.crystalnexus.block.entity.DepotDownloaderBlockEntity;
import net.crystalnexus.block.entity.CrystalSmelterBlockEntity;
import net.crystalnexus.block.entity.CrystalPurifierBlockEntity;
import net.crystalnexus.block.entity.CrystalGuideBlockEntity;
import net.crystalnexus.block.entity.CrystalEnergyGuideBlockEntity;
import net.crystalnexus.block.entity.CrystalCrusherBlockEntity;
import net.crystalnexus.block.entity.CrystalAccepterBlockEntity;
import net.crystalnexus.block.entity.CraftingFactoryBlockEntity;
import net.crystalnexus.block.entity.ConveyerBeltOutputBlockEntity;
import net.crystalnexus.block.entity.ConveyerBeltInputBlockEntity;
import net.crystalnexus.block.entity.ConveyerBeltBlockEntity;
import net.crystalnexus.block.entity.ContainerBlockEntity;
import net.crystalnexus.block.entity.ConductiveEnergySplitterBlockEntity;
import net.crystalnexus.block.entity.ConductiveEnergyRefractorBlockEntity;
import net.crystalnexus.block.entity.ConductiveEnergyGuideBlockEntity;
import net.crystalnexus.block.entity.ComputationClusterBlockEntity;
import net.crystalnexus.block.entity.CircuitPressBlockEntity;
import net.crystalnexus.block.entity.ChlorophyteSmelterBlockEntity;
import net.crystalnexus.block.entity.ChlorophyteAcceleratorBlockEntity;
import net.crystalnexus.block.entity.ChemicalReactionChamberBlockEntity;
import net.crystalnexus.block.entity.BluTNTBlockEntity;
import net.crystalnexus.block.entity.BlockPlacerBlockEntity;
import net.crystalnexus.block.entity.BiomaticSimulatorBlockEntity;
import net.crystalnexus.block.entity.BiomaticConstructorBlockEntity;
import net.crystalnexus.block.entity.BiomaticComposterBlockEntity;
import net.crystalnexus.block.entity.BatteryMonitorBlockEntity;
import net.crystalnexus.block.entity.BatteryBlockEntity;
import net.crystalnexus.block.entity.BasicEnergyCableBlockEntity;
import net.crystalnexus.CrystalnexusMod;

@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD)
public class CrystalnexusModBlockEntities {
	public static final DeferredRegister<BlockEntityType<?>> REGISTRY = DeferredRegister.create(BuiltInRegistries.BLOCK_ENTITY_TYPE, CrystalnexusMod.MODID);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CRYSTAL_PURIFIER = register("crystal_purifier", CrystalnexusModBlocks.CRYSTAL_PURIFIER, CrystalPurifierBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CRYSTAL_ACCEPTER = register("crystal_accepter", CrystalnexusModBlocks.CRYSTAL_ACCEPTER, CrystalAccepterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CRYSTAL_CRUSHER = register("crystal_crusher", CrystalnexusModBlocks.CRYSTAL_CRUSHER, CrystalCrusherBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DUST_SEPARATOR = register("dust_separator", CrystalnexusModBlocks.DUST_SEPARATOR, DustSeparatorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CRYSTAL_GUIDE = register("crystal_guide", CrystalnexusModBlocks.CRYSTAL_GUIDE, CrystalGuideBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ITEM_COLLECTOR = register("item_collector", CrystalnexusModBlocks.ITEM_COLLECTOR, ItemCollectorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> EXTRACTINATOR = register("extractinator", CrystalnexusModBlocks.EXTRACTINATOR, ExtractinatorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CHLOROPHYTE_ACCELERATOR = register("chlorophyte_accelerator", CrystalnexusModBlocks.CHLOROPHYTE_ACCELERATOR, ChlorophyteAcceleratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> METALLURGIC_RECRYSTALLIZER = register("metallurgic_recrystallizer", CrystalnexusModBlocks.METALLURGIC_RECRYSTALLIZER, MetallurgicRecrystallizerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> REACTOR_COMPUTER = register("reactor_computer", CrystalnexusModBlocks.REACTOR_COMPUTER, ReactorComputerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> REACTOR_ENERGY_OUTPUT = register("reactor_energy_output", CrystalnexusModBlocks.REACTOR_ENERGY_OUTPUT, ReactorEnergyOutputBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> REACTOR_FLUID_INPUT = register("reactor_fluid_input", CrystalnexusModBlocks.REACTOR_FLUID_INPUT, ReactorFluidInputBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> IRON_SMELTER = register("iron_smelter", CrystalnexusModBlocks.IRON_SMELTER, IronSmelterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CRYSTAL_SMELTER = register("crystal_smelter", CrystalnexusModBlocks.CRYSTAL_SMELTER, CrystalSmelterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INVERTIUM_SMELTER = register("invertium_smelter", CrystalnexusModBlocks.INVERTIUM_SMELTER, InvertiumSmelterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CHLOROPHYTE_SMELTER = register("chlorophyte_smelter", CrystalnexusModBlocks.CHLOROPHYTE_SMELTER, ChlorophyteSmelterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> TESSERACT = register("tesseract", CrystalnexusModBlocks.TESSERACT, TesseractBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> TESSERACT_OUTPUT = register("tesseract_output", CrystalnexusModBlocks.TESSERACT_OUTPUT, TesseractOutputBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CIRCUIT_PRESS = register("circuit_press", CrystalnexusModBlocks.CIRCUIT_PRESS, CircuitPressBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> BLU_TNT = register("blu_tnt", CrystalnexusModBlocks.BLU_TNT, BluTNTBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> FACTORY_CONTROLLER = register("factory_controller", CrystalnexusModBlocks.FACTORY_CONTROLLER, FactoryControllerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> FACTORY_ITEM_CONTROLLER = register("factory_item_controller", CrystalnexusModBlocks.FACTORY_ITEM_CONTROLLER, FactoryItemControllerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> FACTORY_OUTPUT_CONTROLLER = register("factory_output_controller", CrystalnexusModBlocks.FACTORY_OUTPUT_CONTROLLER, FactoryOutputControllerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INVERTER = register("inverter", CrystalnexusModBlocks.INVERTER, InverterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> REACTION_CHAMBER_COMPUTER = register("reaction_chamber_computer", CrystalnexusModBlocks.REACTION_CHAMBER_COMPUTER, ReactionChamberComputerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> REACTION_ENERGY_INPUT = register("reaction_energy_input", CrystalnexusModBlocks.REACTION_ENERGY_INPUT, ReactionEnergyInputBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ULTIMA_SMELTER = register("ultima_smelter", CrystalnexusModBlocks.ULTIMA_SMELTER, UltimaSmelterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ENERGY_EXTRACTOR = register("energy_extractor", CrystalnexusModBlocks.ENERGY_EXTRACTOR, EnergyExtractorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CRYSTAL_ENERGY_GUIDE = register("crystal_energy_guide", CrystalnexusModBlocks.CRYSTAL_ENERGY_GUIDE, CrystalEnergyGuideBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ENERGY_REFRACTOR = register("energy_refractor", CrystalnexusModBlocks.ENERGY_REFRACTOR, EnergyRefractorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ENERGY_SPLITTER = register("energy_splitter", CrystalnexusModBlocks.ENERGY_SPLITTER, EnergySplitterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MATTER_TRANSMUTATION_TABLE = register("matter_transmutation_table", CrystalnexusModBlocks.MATTER_TRANSMUTATION_TABLE, MatterTransmutationTableBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> BLOCK_PLACER = register("block_placer", CrystalnexusModBlocks.BLOCK_PLACER, BlockPlacerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> SINGULARITY_COMPRESSOR = register("singularity_compressor", CrystalnexusModBlocks.SINGULARITY_COMPRESSOR, SingularityCompressorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ZERO_POINT = register("zero_point", CrystalnexusModBlocks.ZERO_POINT, ZeroPointBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CHEMICAL_REACTION_CHAMBER = register("chemical_reaction_chamber", CrystalnexusModBlocks.CHEMICAL_REACTION_CHAMBER, ChemicalReactionChamberBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CONTAINER = register("container", CrystalnexusModBlocks.CONTAINER, ContainerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CONDUCTIVE_ENERGY_GUIDE = register("conductive_energy_guide", CrystalnexusModBlocks.CONDUCTIVE_ENERGY_GUIDE, ConductiveEnergyGuideBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CONDUCTIVE_ENERGY_REFRACTOR = register("conductive_energy_refractor", CrystalnexusModBlocks.CONDUCTIVE_ENERGY_REFRACTOR, ConductiveEnergyRefractorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CONDUCTIVE_ENERGY_SPLITTER = register("conductive_energy_splitter", CrystalnexusModBlocks.CONDUCTIVE_ENERGY_SPLITTER, ConductiveEnergySplitterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> QUANTUM_MINER = register("quantum_miner", CrystalnexusModBlocks.QUANTUM_MINER, QuantumMinerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> BATTERY = register("battery", CrystalnexusModBlocks.BATTERY, BatteryBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> EE_BATTERY = register("ee_battery", CrystalnexusModBlocks.EE_BATTERY, EEBatteryBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> TURBINE = register("turbine", CrystalnexusModBlocks.TURBINE, TurbineBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MACHINEBLOCK = register("machineblock", CrystalnexusModBlocks.MACHINEBLOCK, MachineblockBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ORE_PROCESSOR = register("ore_processor", CrystalnexusModBlocks.ORE_PROCESSOR, OreProcessorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MACHINE_CORE = register("machine_core", CrystalnexusModBlocks.MACHINE_CORE, MachineCoreBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MACHINE_ENERGY_INPUT = register("machine_energy_input", CrystalnexusModBlocks.MACHINE_ENERGY_INPUT, MachineEnergyInputBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> BIOMATIC_COMPOSTER = register("biomatic_composter", CrystalnexusModBlocks.BIOMATIC_COMPOSTER, BiomaticComposterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> BIOMATIC_CONSTRUCTOR = register("biomatic_constructor", CrystalnexusModBlocks.BIOMATIC_CONSTRUCTOR, BiomaticConstructorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> BIOMATIC_SIMULATOR = register("biomatic_simulator", CrystalnexusModBlocks.BIOMATIC_SIMULATOR, BiomaticSimulatorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> BATTERY_MONITOR = register("battery_monitor", CrystalnexusModBlocks.BATTERY_MONITOR, BatteryMonitorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MULTIBLOCK_RESEARCH_STATION = register("multiblock_research_station", CrystalnexusModBlocks.MULTIBLOCK_RESEARCH_STATION, MultiblockResearchStationBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> WARP_PAD = register("warp_pad", CrystalnexusModBlocks.WARP_PAD, WarpPadBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> PISTON_GENERATOR = register("piston_generator", CrystalnexusModBlocks.PISTON_GENERATOR, PistonGeneratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INVERT_PISTON_GENERATOR = register("invert_piston_generator", CrystalnexusModBlocks.INVERT_PISTON_GENERATOR, InvertPistonGeneratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> PIPE_STRAIGHT = register("pipe_straight", CrystalnexusModBlocks.PIPE_STRAIGHT, PipeStraightBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> PIPE_JUNCTION = register("pipe_junction", CrystalnexusModBlocks.PIPE_JUNCTION, PipeJunctionBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> STEAM_COLLECTOR = register("steam_collector", CrystalnexusModBlocks.STEAM_COLLECTOR, SteamCollectorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> STEAM_CHAMBER = register("steam_chamber", CrystalnexusModBlocks.STEAM_CHAMBER, SteamChamberBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CONVEYER_BELT = register("conveyer_belt", CrystalnexusModBlocks.CONVEYER_BELT, ConveyerBeltBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CONVEYER_BELT_INPUT = register("conveyer_belt_input", CrystalnexusModBlocks.CONVEYER_BELT_INPUT, ConveyerBeltInputBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CONVEYER_BELT_OUTPUT = register("conveyer_belt_output", CrystalnexusModBlocks.CONVEYER_BELT_OUTPUT, ConveyerBeltOutputBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ITEM_ELEVATOR = register("item_elevator", CrystalnexusModBlocks.ITEM_ELEVATOR, ItemElevatorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ITEM_ELEVATOR_DOWN = register("item_elevator_down", CrystalnexusModBlocks.ITEM_ELEVATOR_DOWN, ItemElevatorDownBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CRAFTING_FACTORY = register("crafting_factory", CrystalnexusModBlocks.CRAFTING_FACTORY, CraftingFactoryBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> NODE_MINER = register("node_miner", CrystalnexusModBlocks.NODE_MINER, NodeMinerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> STEAM_ENGINE = register("steam_engine", CrystalnexusModBlocks.STEAM_ENGINE, SteamEngineBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> STEAM_ENGINE_UPGRADE = register("steam_engine_upgrade", CrystalnexusModBlocks.STEAM_ENGINE_UPGRADE, SteamEngineUpgradeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> SINGULARITY_MATRIX = register("singularity_matrix", CrystalnexusModBlocks.SINGULARITY_MATRIX, SingularityMatrixBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DEPOT_UPLOADER = register("depot_uploader", CrystalnexusModBlocks.DEPOT_UPLOADER, DepotUploaderBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DEPOT_DOWNLOADER = register("depot_downloader", CrystalnexusModBlocks.DEPOT_DOWNLOADER, DepotDownloaderBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ENERGY_CABLE = register("energy_cable", CrystalnexusModBlocks.ENERGY_CABLE, EnergyCableBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> REACTOR_WASTE_OUTPUT = register("reactor_waste_output", CrystalnexusModBlocks.REACTOR_WASTE_OUTPUT, ReactorWasteOutputBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ENERGY_CABLE_MK_2 = register("energy_cable_mk_2", CrystalnexusModBlocks.ENERGY_CABLE_MK_2, EnergyCableMk2BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> BASIC_ENERGY_CABLE = register("basic_energy_cable", CrystalnexusModBlocks.BASIC_ENERGY_CABLE, BasicEnergyCableBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> NODE_EXTRACTOR = register("node_extractor", CrystalnexusModBlocks.NODE_EXTRACTOR, NodeExtractorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> TANK = register("tank", CrystalnexusModBlocks.TANK, TankBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> FLUID_PACKAGER = register("fluid_packager", CrystalnexusModBlocks.FLUID_PACKAGER, FluidPackagerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> SMART_SPLITTER = register("smart_splitter", CrystalnexusModBlocks.SMART_SPLITTER, SmartSplitterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> COMPUTATION_CLUSTER = register("computation_cluster", CrystalnexusModBlocks.COMPUTATION_CLUSTER, ComputationClusterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> PARTICLE_ACCELERATOR_TUBE = register("particle_accelerator_tube", CrystalnexusModBlocks.PARTICLE_ACCELERATOR_TUBE, ParticleAcceleratorTubeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> PARTICLE_ACCELERATOR_CONTROLLER = register("particle_accelerator_controller", CrystalnexusModBlocks.PARTICLE_ACCELERATOR_CONTROLLER,
			ParticleAcceleratorControllerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ELECTROMAGNET = register("electromagnet", CrystalnexusModBlocks.ELECTROMAGNET, ElectromagnetBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> QUARRY = register("quarry", CrystalnexusModBlocks.QUARRY, QuarryBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> RAD_PLACEHOLDER = register("rad_placeholder", CrystalnexusModBlocks.RAD_PLACEHOLDER, RadPlaceholderBlockEntity::new);

	// Start of user code block custom block entities
	// End of user code block custom block entities
	private static DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> register(String registryname, DeferredHolder<Block, Block> block, BlockEntityType.BlockEntitySupplier<?> supplier) {
		return REGISTRY.register(registryname, () -> BlockEntityType.Builder.of(supplier, block.get()).build(null));
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CRYSTAL_PURIFIER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, CRYSTAL_PURIFIER.get(), (blockEntity, side) -> ((CrystalPurifierBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CRYSTAL_ACCEPTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, CRYSTAL_ACCEPTER.get(), (blockEntity, side) -> ((CrystalAccepterBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CRYSTAL_CRUSHER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, CRYSTAL_CRUSHER.get(), (blockEntity, side) -> ((CrystalCrusherBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DUST_SEPARATOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DUST_SEPARATOR.get(), (blockEntity, side) -> ((DustSeparatorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CRYSTAL_GUIDE.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ITEM_COLLECTOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, EXTRACTINATOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, EXTRACTINATOR.get(), (blockEntity, side) -> ((ExtractinatorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CHLOROPHYTE_ACCELERATOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, CHLOROPHYTE_ACCELERATOR.get(), (blockEntity, side) -> ((ChlorophyteAcceleratorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, METALLURGIC_RECRYSTALLIZER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, METALLURGIC_RECRYSTALLIZER.get(), (blockEntity, side) -> ((MetallurgicRecrystallizerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, REACTOR_COMPUTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, REACTOR_COMPUTER.get(), (blockEntity, side) -> ((ReactorComputerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, REACTOR_COMPUTER.get(), (blockEntity, side) -> ((ReactorComputerBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, REACTOR_ENERGY_OUTPUT.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, REACTOR_ENERGY_OUTPUT.get(), (blockEntity, side) -> ((ReactorEnergyOutputBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, REACTOR_FLUID_INPUT.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, REACTOR_FLUID_INPUT.get(), (blockEntity, side) -> ((ReactorFluidInputBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, IRON_SMELTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, IRON_SMELTER.get(), (blockEntity, side) -> ((IronSmelterBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CRYSTAL_SMELTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, CRYSTAL_SMELTER.get(), (blockEntity, side) -> ((CrystalSmelterBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INVERTIUM_SMELTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, INVERTIUM_SMELTER.get(), (blockEntity, side) -> ((InvertiumSmelterBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CHLOROPHYTE_SMELTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, CHLOROPHYTE_SMELTER.get(), (blockEntity, side) -> ((ChlorophyteSmelterBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TESSERACT.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, TESSERACT.get(), (blockEntity, side) -> ((TesseractBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TESSERACT_OUTPUT.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, TESSERACT_OUTPUT.get(), (blockEntity, side) -> ((TesseractOutputBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CIRCUIT_PRESS.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, CIRCUIT_PRESS.get(), (blockEntity, side) -> ((CircuitPressBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, BLU_TNT.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, FACTORY_CONTROLLER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, FACTORY_CONTROLLER.get(), (blockEntity, side) -> ((FactoryControllerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, FACTORY_ITEM_CONTROLLER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, FACTORY_ITEM_CONTROLLER.get(), (blockEntity, side) -> ((FactoryItemControllerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, FACTORY_OUTPUT_CONTROLLER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, FACTORY_OUTPUT_CONTROLLER.get(), (blockEntity, side) -> ((FactoryOutputControllerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INVERTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, INVERTER.get(), (blockEntity, side) -> ((InverterBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, REACTION_CHAMBER_COMPUTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, REACTION_CHAMBER_COMPUTER.get(), (blockEntity, side) -> ((ReactionChamberComputerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, REACTION_ENERGY_INPUT.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, REACTION_ENERGY_INPUT.get(), (blockEntity, side) -> ((ReactionEnergyInputBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ULTIMA_SMELTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, ULTIMA_SMELTER.get(), (blockEntity, side) -> ((UltimaSmelterBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ENERGY_EXTRACTOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, ENERGY_EXTRACTOR.get(), (blockEntity, side) -> ((EnergyExtractorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CRYSTAL_ENERGY_GUIDE.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, CRYSTAL_ENERGY_GUIDE.get(), (blockEntity, side) -> ((CrystalEnergyGuideBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ENERGY_REFRACTOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ENERGY_SPLITTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MATTER_TRANSMUTATION_TABLE.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MATTER_TRANSMUTATION_TABLE.get(), (blockEntity, side) -> ((MatterTransmutationTableBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, BLOCK_PLACER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, BLOCK_PLACER.get(), (blockEntity, side) -> ((BlockPlacerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SINGULARITY_COMPRESSOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, SINGULARITY_COMPRESSOR.get(), (blockEntity, side) -> ((SingularityCompressorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ZERO_POINT.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, ZERO_POINT.get(), (blockEntity, side) -> ((ZeroPointBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CHEMICAL_REACTION_CHAMBER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, CHEMICAL_REACTION_CHAMBER.get(), (blockEntity, side) -> ((ChemicalReactionChamberBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CONTAINER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CONDUCTIVE_ENERGY_GUIDE.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, CONDUCTIVE_ENERGY_GUIDE.get(), (blockEntity, side) -> ((ConductiveEnergyGuideBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CONDUCTIVE_ENERGY_REFRACTOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CONDUCTIVE_ENERGY_SPLITTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, QUANTUM_MINER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, QUANTUM_MINER.get(), (blockEntity, side) -> ((QuantumMinerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, BATTERY.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, BATTERY.get(), (blockEntity, side) -> ((BatteryBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, EE_BATTERY.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, EE_BATTERY.get(), (blockEntity, side) -> ((EEBatteryBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TURBINE.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, TURBINE.get(), (blockEntity, side) -> ((TurbineBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MACHINEBLOCK.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ORE_PROCESSOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, ORE_PROCESSOR.get(), (blockEntity, side) -> ((OreProcessorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MACHINE_CORE.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MACHINE_ENERGY_INPUT.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MACHINE_ENERGY_INPUT.get(), (blockEntity, side) -> ((MachineEnergyInputBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, BIOMATIC_COMPOSTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, BIOMATIC_COMPOSTER.get(), (blockEntity, side) -> ((BiomaticComposterBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, BIOMATIC_CONSTRUCTOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, BIOMATIC_CONSTRUCTOR.get(), (blockEntity, side) -> ((BiomaticConstructorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, BIOMATIC_SIMULATOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, BIOMATIC_SIMULATOR.get(), (blockEntity, side) -> ((BiomaticSimulatorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, BATTERY_MONITOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MULTIBLOCK_RESEARCH_STATION.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, WARP_PAD.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, WARP_PAD.get(), (blockEntity, side) -> ((WarpPadBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, PISTON_GENERATOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, PISTON_GENERATOR.get(), (blockEntity, side) -> ((PistonGeneratorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, PISTON_GENERATOR.get(), (blockEntity, side) -> ((PistonGeneratorBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INVERT_PISTON_GENERATOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, INVERT_PISTON_GENERATOR.get(), (blockEntity, side) -> ((InvertPistonGeneratorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, INVERT_PISTON_GENERATOR.get(), (blockEntity, side) -> ((InvertPistonGeneratorBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, PIPE_STRAIGHT.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, PIPE_STRAIGHT.get(), (blockEntity, side) -> ((PipeStraightBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, PIPE_JUNCTION.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, PIPE_JUNCTION.get(), (blockEntity, side) -> ((PipeJunctionBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, STEAM_COLLECTOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, STEAM_COLLECTOR.get(), (blockEntity, side) -> ((SteamCollectorBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, STEAM_CHAMBER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CONVEYER_BELT.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CONVEYER_BELT_INPUT.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CONVEYER_BELT_OUTPUT.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ITEM_ELEVATOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ITEM_ELEVATOR_DOWN.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CRAFTING_FACTORY.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, CRAFTING_FACTORY.get(), (blockEntity, side) -> ((CraftingFactoryBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, NODE_MINER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, NODE_MINER.get(), (blockEntity, side) -> ((NodeMinerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, STEAM_ENGINE.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, STEAM_ENGINE.get(), (blockEntity, side) -> ((SteamEngineBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, STEAM_ENGINE.get(), (blockEntity, side) -> ((SteamEngineBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, STEAM_ENGINE_UPGRADE.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, STEAM_ENGINE_UPGRADE.get(), (blockEntity, side) -> ((SteamEngineUpgradeBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, STEAM_ENGINE_UPGRADE.get(), (blockEntity, side) -> ((SteamEngineUpgradeBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SINGULARITY_MATRIX.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DEPOT_UPLOADER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DEPOT_DOWNLOADER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ENERGY_CABLE.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, ENERGY_CABLE.get(), (blockEntity, side) -> ((EnergyCableBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, REACTOR_WASTE_OUTPUT.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ENERGY_CABLE_MK_2.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, ENERGY_CABLE_MK_2.get(), (blockEntity, side) -> ((EnergyCableMk2BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, BASIC_ENERGY_CABLE.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, BASIC_ENERGY_CABLE.get(), (blockEntity, side) -> ((BasicEnergyCableBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, NODE_EXTRACTOR.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, NODE_EXTRACTOR.get(), (blockEntity, side) -> ((NodeExtractorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, NODE_EXTRACTOR.get(), (blockEntity, side) -> ((NodeExtractorBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TANK.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, TANK.get(), (blockEntity, side) -> ((TankBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, FLUID_PACKAGER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, FLUID_PACKAGER.get(), (blockEntity, side) -> ((FluidPackagerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, FLUID_PACKAGER.get(), (blockEntity, side) -> ((FluidPackagerBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SMART_SPLITTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, COMPUTATION_CLUSTER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, COMPUTATION_CLUSTER.get(), (blockEntity, side) -> ((ComputationClusterBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, PARTICLE_ACCELERATOR_TUBE.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, PARTICLE_ACCELERATOR_CONTROLLER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ELECTROMAGNET.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, ELECTROMAGNET.get(), (blockEntity, side) -> ((ElectromagnetBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, QUARRY.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, QUARRY.get(), (blockEntity, side) -> ((QuarryBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, RAD_PLACEHOLDER.get(), (blockEntity, side) -> new SidedInvWrapper((WorldlyContainer) blockEntity, side));
	}
}