package net.crystalnexus.client.preview;

import net.crystalnexus.init.CrystalnexusModBlocks;
import net.minecraft.world.level.block.state.BlockState;

import java.util.ArrayList;
import java.util.List;

public class ZeroPointTemplates {

    public static List<ZeroPointPreviewRenderer.GhostBlock> getTemplate(String id) {
        if (!"zeropoint_multiblock_v1".equals(id)) return List.of();

        ArrayList<ZeroPointPreviewRenderer.GhostBlock> out = new ArrayList<>(512);

        // Map the names your generator used -> actual BlockStates
        BlockState CARBON_BLOCK = CrystalnexusModBlocks.CARBON_BLOCK.get().defaultBlockState();
        BlockState CARBON_GLASS = CrystalnexusModBlocks.CARBON_GLASS.get().defaultBlockState();
        BlockState CARBON_MACHINE_FRAME = CrystalnexusModBlocks.CARBON_MACHINE_FRAME.get().defaultBlockState();
        BlockState ZERO_POINT = CrystalnexusModBlocks.ZERO_POINT.get().defaultBlockState();

        add(out, -11, -1,  -3, CARBON_BLOCK);
        add(out, -11, -1,  -2, CARBON_BLOCK);
        add(out, -11, -1,  -1, CARBON_BLOCK);
        add(out, -11, -1,   0, CARBON_BLOCK);
        add(out, -11, -1,   1, CARBON_BLOCK);
        add(out, -11, -1,   2, CARBON_BLOCK);
        add(out, -11, -1,   3, CARBON_BLOCK);
        add(out, -10, -1,  -5, CARBON_BLOCK);
        add(out, -10, -1,  -4, CARBON_BLOCK);
        add(out, -10, -1,   4, CARBON_BLOCK);
        add(out, -10, -1,   5, CARBON_BLOCK);
        add(out,  -9, -1,  -7, CARBON_BLOCK);
        add(out,  -9, -1,  -6, CARBON_BLOCK);
        add(out,  -9, -1,   6, CARBON_BLOCK);
        add(out,  -9, -1,   7, CARBON_BLOCK);
        add(out,  -8, -1,  -8, CARBON_BLOCK);
        add(out,  -8, -1,   8, CARBON_BLOCK);
        add(out,  -7, -1,  -9, CARBON_BLOCK);
        add(out,  -7, -1,   9, CARBON_BLOCK);
        add(out,  -6, -1,  -9, CARBON_BLOCK);
        add(out,  -6, -1,   9, CARBON_BLOCK);
        add(out,  -5, -1, -10, CARBON_BLOCK);
        add(out,  -5, -1,  10, CARBON_BLOCK);
        add(out,  -4, -1, -10, CARBON_BLOCK);
        add(out,  -4, -1,  10, CARBON_BLOCK);
        add(out,  -3, -1, -11, CARBON_BLOCK);
        add(out,  -3, -1,  11, CARBON_BLOCK);
        add(out,  -2, -1, -11, CARBON_BLOCK);
        add(out,  -2, -1,  11, CARBON_BLOCK);
        add(out,  -1, -1, -11, CARBON_BLOCK);
        add(out,  -1, -1,  11, CARBON_BLOCK);
        add(out,   0, -1, -11, CARBON_BLOCK);
        add(out,   0, -1,  11, CARBON_BLOCK);
        add(out,   1, -1, -11, CARBON_BLOCK);
        add(out,   1, -1,  11, CARBON_BLOCK);
        add(out,   2, -1, -11, CARBON_BLOCK);
        add(out,   2, -1,  11, CARBON_BLOCK);
        add(out,   3, -1, -11, CARBON_BLOCK);
        add(out,   3, -1,  11, CARBON_BLOCK);
        add(out,   4, -1, -10, CARBON_BLOCK);
        add(out,   4, -1,  10, CARBON_BLOCK);
        add(out,   5, -1, -10, CARBON_BLOCK);
        add(out,   5, -1,  10, CARBON_BLOCK);
        add(out,   6, -1,  -9, CARBON_BLOCK);
        add(out,   6, -1,   9, CARBON_BLOCK);
        add(out,   7, -1,  -9, CARBON_BLOCK);
        add(out,   7, -1,   9, CARBON_BLOCK);
        add(out,   8, -1,  -8, CARBON_BLOCK);
        add(out,   8, -1,   8, CARBON_BLOCK);
        add(out,   9, -1,  -7, CARBON_BLOCK);
        add(out,   9, -1,  -6, CARBON_BLOCK);
        add(out,   9, -1,   6, CARBON_BLOCK);
        add(out,   9, -1,   7, CARBON_BLOCK);
        add(out,  10, -1,  -5, CARBON_BLOCK);
        add(out,  10, -1,  -4, CARBON_BLOCK);
        add(out,  10, -1,   4, CARBON_BLOCK);
        add(out,  10, -1,   5, CARBON_BLOCK);
        add(out,  11, -1,  -3, CARBON_BLOCK);
        add(out,  11, -1,  -2, CARBON_BLOCK);
        add(out,  11, -1,  -1, CARBON_BLOCK);
        add(out,  11, -1,   0, CARBON_BLOCK);
        add(out,  11, -1,   1, CARBON_BLOCK);
        add(out,  11, -1,   2, CARBON_BLOCK);
        add(out,  11, -1,   3, CARBON_BLOCK);
        add(out, -12,  0,  -3, CARBON_BLOCK);
        add(out, -12,  0,  -2, CARBON_GLASS);
        add(out, -12,  0,  -1, CARBON_GLASS);
        add(out, -12,  0,   0, CARBON_GLASS);
        add(out, -12,  0,   1, CARBON_GLASS);
        add(out, -12,  0,   2, CARBON_GLASS);
        add(out, -12,  0,   3, CARBON_BLOCK);
        add(out, -11,  0,  -5, CARBON_BLOCK);
        add(out, -11,  0,  -4, CARBON_BLOCK);
        add(out, -11,  0,   0, CARBON_MACHINE_FRAME);
        add(out, -11,  0,   4, CARBON_BLOCK);
        add(out, -11,  0,   5, CARBON_BLOCK);
        add(out, -10,  0,  -7, CARBON_BLOCK);
        add(out, -10,  0,  -6, CARBON_BLOCK);
        add(out, -10,  0,   0, CARBON_MACHINE_FRAME);
        add(out, -10,  0,   6, CARBON_BLOCK);
        add(out, -10,  0,   7, CARBON_BLOCK);
        add(out,  -9,  0,  -8, CARBON_BLOCK);
        add(out,  -9,  0,   0, CARBON_MACHINE_FRAME);
        add(out,  -9,  0,   8, CARBON_BLOCK);
        add(out,  -8,  0,  -9, CARBON_BLOCK);
        add(out,  -8,  0,   0, CARBON_MACHINE_FRAME);
        add(out,  -8,  0,   9, CARBON_BLOCK);
        add(out,  -7,  0, -10, CARBON_BLOCK);
        add(out,  -7,  0,   0, CARBON_MACHINE_FRAME);
        add(out,  -7,  0,  10, CARBON_BLOCK);
        add(out,  -6,  0, -10, CARBON_BLOCK);
        add(out,  -6,  0,   0, CARBON_MACHINE_FRAME);
        add(out,  -6,  0,  10, CARBON_BLOCK);
        add(out,  -5,  0, -11, CARBON_BLOCK);
        add(out,  -5,  0,   0, CARBON_MACHINE_FRAME);
        add(out,  -5,  0,  11, CARBON_BLOCK);
        add(out,  -4,  0, -11, CARBON_BLOCK);
        add(out,  -4,  0,   0, CARBON_MACHINE_FRAME);
        add(out,  -4,  0,  11, CARBON_BLOCK);
        add(out,  -3,  0, -12, CARBON_BLOCK);
        add(out,  -3,  0,   0, CARBON_MACHINE_FRAME);
        add(out,  -3,  0,  12, CARBON_BLOCK);
        add(out,  -2,  0, -12, CARBON_GLASS);
        add(out,  -2,  0,  -1, CARBON_MACHINE_FRAME);
        add(out,  -2,  0,   0, CARBON_MACHINE_FRAME);
        add(out,  -2,  0,   1, CARBON_MACHINE_FRAME);
        add(out,  -2,  0,  12, CARBON_GLASS);
        add(out,  -1,  0, -12, CARBON_GLASS);
        add(out,  -1,  0,  -2, CARBON_MACHINE_FRAME);
        add(out,  -1,  0,  -1, CARBON_MACHINE_FRAME);
        add(out,  -1,  0,   1, CARBON_MACHINE_FRAME);
        add(out,  -1,  0,   2, CARBON_MACHINE_FRAME);
        add(out,  -1,  0,  12, CARBON_GLASS);
        add(out,   0,  0, -12, CARBON_GLASS);
        add(out,   0,  0, -11, CARBON_MACHINE_FRAME);
        add(out,   0,  0, -10, CARBON_MACHINE_FRAME);
        add(out,   0,  0,  -9, CARBON_MACHINE_FRAME);
        add(out,   0,  0,  -8, CARBON_MACHINE_FRAME);
        add(out,   0,  0,  -7, CARBON_MACHINE_FRAME);
        add(out,   0,  0,  -6, CARBON_MACHINE_FRAME);
        add(out,   0,  0,  -5, CARBON_MACHINE_FRAME);
        add(out,   0,  0,  -4, CARBON_MACHINE_FRAME);
        add(out,   0,  0,  -3, CARBON_MACHINE_FRAME);
        add(out,   0,  0,  -2, CARBON_MACHINE_FRAME);
        add(out,   0,  0,   2, CARBON_MACHINE_FRAME);
        add(out,   0,  0,   3, CARBON_MACHINE_FRAME);
        add(out,   0,  0,   4, CARBON_MACHINE_FRAME);
        add(out,   0,  0,   5, CARBON_MACHINE_FRAME);
        add(out,   0,  0,   6, CARBON_MACHINE_FRAME);
        add(out,   0,  0,   7, CARBON_MACHINE_FRAME);
        add(out,   0,  0,   8, CARBON_MACHINE_FRAME);
        add(out,   0,  0,   9, CARBON_MACHINE_FRAME);
        add(out,   0,  0,  10, CARBON_MACHINE_FRAME);
        add(out,   0,  0,  11, CARBON_MACHINE_FRAME);
        add(out,   0,  0,  12, CARBON_GLASS);
        add(out,   1,  0, -12, CARBON_GLASS);
        add(out,   1,  0,  -2, CARBON_MACHINE_FRAME);
        add(out,   1,  0,  -1, CARBON_MACHINE_FRAME);
        add(out,   1,  0,   1, CARBON_MACHINE_FRAME);
        add(out,   1,  0,   2, CARBON_MACHINE_FRAME);
        add(out,   1,  0,  12, CARBON_GLASS);
        add(out,   2,  0, -12, CARBON_GLASS);
        add(out,   2,  0,  -1, CARBON_MACHINE_FRAME);
        add(out,   2,  0,   0, CARBON_MACHINE_FRAME);
        add(out,   2,  0,   1, CARBON_MACHINE_FRAME);
        add(out,   2,  0,  12, CARBON_GLASS);
        add(out,   3,  0, -12, CARBON_BLOCK);
        add(out,   3,  0,   0, CARBON_MACHINE_FRAME);
        add(out,   3,  0,  12, CARBON_BLOCK);
        add(out,   4,  0, -11, CARBON_BLOCK);
        add(out,   4,  0,   0, CARBON_MACHINE_FRAME);
        add(out,   4,  0,  11, CARBON_BLOCK);
        add(out,   5,  0, -11, CARBON_BLOCK);
        add(out,   5,  0,   0, CARBON_MACHINE_FRAME);
        add(out,   5,  0,  11, CARBON_BLOCK);
        add(out,   6,  0, -10, CARBON_BLOCK);
        add(out,   6,  0,   0, CARBON_MACHINE_FRAME);
        add(out,   6,  0,  10, CARBON_BLOCK);
        add(out,   7,  0, -10, CARBON_BLOCK);
        add(out,   7,  0,   0, CARBON_MACHINE_FRAME);
        add(out,   7,  0,  10, CARBON_BLOCK);
        add(out,   8,  0,  -9, CARBON_BLOCK);
        add(out,   8,  0,   0, CARBON_MACHINE_FRAME);
        add(out,   8,  0,   9, CARBON_BLOCK);
        add(out,   9,  0,  -8, CARBON_BLOCK);
        add(out,   9,  0,   0, CARBON_MACHINE_FRAME);
        add(out,   9,  0,   8, CARBON_BLOCK);
        add(out,  10,  0,  -7, CARBON_BLOCK);
        add(out,  10,  0,  -6, CARBON_BLOCK);
        add(out,  10,  0,   0, CARBON_MACHINE_FRAME);
        add(out,  10,  0,   6, CARBON_BLOCK);
        add(out,  10,  0,   7, CARBON_BLOCK);
        add(out,  11,  0,  -5, CARBON_BLOCK);
        add(out,  11,  0,  -4, CARBON_BLOCK);
        add(out,  11,  0,   0, CARBON_MACHINE_FRAME);
        add(out,  11,  0,   4, CARBON_BLOCK);
        add(out,  11,  0,   5, CARBON_BLOCK);
        add(out,  12,  0,  -3, CARBON_BLOCK);
        add(out,  12,  0,  -2, CARBON_GLASS);
        add(out,  12,  0,  -1, CARBON_GLASS);
        add(out,  12,  0,   0, CARBON_GLASS);
        add(out,  12,  0,   1, CARBON_GLASS);
        add(out,  12,  0,   2, CARBON_GLASS);
        add(out,  12,  0,   3, CARBON_BLOCK);
        add(out, -11,  1,  -3, CARBON_BLOCK);
        add(out, -11,  1,  -2, CARBON_BLOCK);
        add(out, -11,  1,  -1, CARBON_BLOCK);
        add(out, -11,  1,   0, CARBON_BLOCK);
        add(out, -11,  1,   1, CARBON_BLOCK);
        add(out, -11,  1,   2, CARBON_BLOCK);
        add(out, -11,  1,   3, CARBON_BLOCK);
        add(out, -10,  1,  -5, CARBON_BLOCK);
        add(out, -10,  1,  -4, CARBON_BLOCK);
        add(out, -10,  1,   4, CARBON_BLOCK);
        add(out, -10,  1,   5, CARBON_BLOCK);
        add(out,  -9,  1,  -7, CARBON_BLOCK);
        add(out,  -9,  1,  -6, CARBON_BLOCK);
        add(out,  -9,  1,   6, CARBON_BLOCK);
        add(out,  -9,  1,   7, CARBON_BLOCK);
        add(out,  -8,  1,  -8, CARBON_BLOCK);
        add(out,  -8,  1,   8, CARBON_BLOCK);
        add(out,  -7,  1,  -9, CARBON_BLOCK);
        add(out,  -7,  1,   9, CARBON_BLOCK);
        add(out,  -6,  1,  -9, CARBON_BLOCK);
        add(out,  -6,  1,   9, CARBON_BLOCK);
        add(out,  -5,  1, -10, CARBON_BLOCK);
        add(out,  -5,  1,  10, CARBON_BLOCK);
        add(out,  -4,  1, -10, CARBON_BLOCK);
        add(out,  -4,  1,  10, CARBON_BLOCK);
        add(out,  -3,  1, -11, CARBON_BLOCK);
        add(out,  -3,  1,  11, CARBON_BLOCK);
        add(out,  -2,  1, -11, CARBON_BLOCK);
        add(out,  -2,  1,  11, CARBON_BLOCK);
        add(out,  -1,  1, -11, CARBON_BLOCK);
        add(out,  -1,  1,  11, CARBON_BLOCK);
        add(out,   0,  1, -11, CARBON_BLOCK);
        add(out,   0,  1,  11, CARBON_BLOCK);
        add(out,   1,  1, -11, CARBON_BLOCK);
        add(out,   1,  1,  11, CARBON_BLOCK);
        add(out,   2,  1, -11, CARBON_BLOCK);
        add(out,   2,  1,  11, CARBON_BLOCK);
        add(out,   3,  1, -11, CARBON_BLOCK);
        add(out,   3,  1,  11, CARBON_BLOCK);
        add(out,   4,  1, -10, CARBON_BLOCK);
        add(out,   4,  1,  10, CARBON_BLOCK);
        add(out,   5,  1, -10, CARBON_BLOCK);
        add(out,   5,  1,  10, CARBON_BLOCK);
        add(out,   6,  1,  -9, CARBON_BLOCK);
        add(out,   6,  1,   9, CARBON_BLOCK);
        add(out,   7,  1,  -9, CARBON_BLOCK);
        add(out,   7,  1,   9, CARBON_BLOCK);
        add(out,   8,  1,  -8, CARBON_BLOCK);
        add(out,   8,  1,   8, CARBON_BLOCK);
        add(out,   9,  1,  -7, CARBON_BLOCK);
        add(out,   9,  1,  -6, CARBON_BLOCK);
        add(out,   9,  1,   6, CARBON_BLOCK);
        add(out,   9,  1,   7, CARBON_BLOCK);
        add(out,  10,  1,  -5, CARBON_BLOCK);
        add(out,  10,  1,  -4, CARBON_BLOCK);
        add(out,  10,  1,   4, CARBON_BLOCK);
        add(out,  10,  1,   5, CARBON_BLOCK);
        add(out,  11,  1,  -3, CARBON_BLOCK);
        add(out,  11,  1,  -2, CARBON_BLOCK);
        add(out,  11,  1,  -1, CARBON_BLOCK);
        add(out,  11,  1,   0, CARBON_BLOCK);
        add(out,  11,  1,   1, CARBON_BLOCK);
        add(out,  11,  1,   2, CARBON_BLOCK);
        add(out,  11,  1,   3, CARBON_BLOCK);
        add(out,   0,  0,   0, ZERO_POINT);


        return out;
    }

    private static void add(List<ZeroPointPreviewRenderer.GhostBlock> out,
                            int dx, int dy, int dz, BlockState state) {
        out.add(new ZeroPointPreviewRenderer.GhostBlock(dx, dy, dz, state));
    }
}
